import { useCallback, useEffect, useMemo, useState, type CSSProperties, type ReactNode } from 'react';
import { BookOpen, Boxes, Calendar, ChevronRight, FileText, Link2Off, Pencil, Plus, Search, Settings, ToggleLeft, ToggleRight, Trash2, X } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useServicos } from '../../hooks/useServicos';
import { useMaquininhaConfig } from '../../hooks/useMaquininhaConfig';
import { useGoogleCalendar } from '../../hooks/useGoogleCalendar';
import { useToast } from '../../hooks/useToast';
import { Skeleton } from '../../components/ui/Skeleton';
import { MaterialsSection } from './MaterialsSection';
import { ComboCompositionEditor } from './ComboCompositionEditor';
import type { ContractTemplate, MaquininhaConfig, Service, ServiceType } from '../../types';

type Section = 'servicos' | 'contratos' | 'materiais' | 'config';
type SortMode = 'name' | 'price_desc' | 'price_asc' | 'margin_desc';

const SERVICE_TYPE_LABELS: Record<ServiceType, string> = { servico: 'Serviço', combo: 'Combo', plano: 'Plano', produto: 'Produto' };
const TYPE_BADGE_STYLE: Record<ServiceType, CSSProperties> = {
  servico: { background: '#dbeafe', color: '#1d4ed8' }, combo: { background: '#ede9fe', color: '#6d28d9' }, plano: { background: '#fef3c7', color: '#b45309' }, produto: { background: '#dcfce7', color: '#15803d' },
};
const normalizeMoneyInput = (value: string) => { const clean = value.replace(/[^\d.,]/g, ''); if (!clean) return ''; const separatorIndex = Math.max(clean.lastIndexOf(','), clean.lastIndexOf('.')); if (separatorIndex === -1) return clean; const integerPart = clean.slice(0, separatorIndex).replace(/[.,]/g, ''); const decimalPart = clean.slice(separatorIndex + 1).replace(/[.,]/g, '').slice(0, 2); return `${integerPart},${decimalPart}`; };
const parseMoneyInput = (value: string) => { const parsed = Number(value.replace(',', '.')); return Number.isFinite(parsed) ? parsed : 0; };
const emptyService = (): Omit<Service, 'id' | 'user_id' | 'created_at'> => ({ name: '', type: 'servico', price: 0, cost_per_unit: 0, duration_minutes: null, return_min_days: null, return_max_days: null, technical_sheet: null, active: true, is_injectable: false });

function ServiceDrawer({ initial, services, onSave, onClose }: { initial?: Service; services: Service[]; onSave: (data: Omit<Service, 'id' | 'user_id' | 'created_at'>) => Promise<unknown>; onClose: () => void }) {
  const [form, setForm] = useState(initial ? { name: initial.name, type: initial.type, price: initial.price, cost_per_unit: initial.cost_per_unit, duration_minutes: initial.duration_minutes, return_min_days: initial.return_min_days, return_max_days: initial.return_max_days, technical_sheet: initial.technical_sheet, active: initial.active, is_injectable: initial.is_injectable } : emptyService());
  const [priceInput, setPriceInput] = useState(initial ? initial.price.toFixed(2).replace('.', ',') : '');
  const [costInput, setCostInput] = useState(initial ? initial.cost_per_unit.toFixed(2).replace('.', ',') : '');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const set = (key: keyof typeof form, value: unknown) => setForm(current => ({ ...current, [key]: value }));
  const handleSubmit = async () => {
    if (!form.name.trim()) { setError('Nome obrigatório'); return; }
    setSaving(true); setError('');
    try {
      await onSave({ ...form, price: parseMoneyInput(priceInput), cost_per_unit: parseMoneyInput(costInput) } as Omit<Service, 'id' | 'user_id' | 'created_at'>);
      onClose();
    } catch (err) { setError(err instanceof Error ? err.message : 'Erro ao salvar'); }
    finally { setSaving(false); }
  };
  return <div className="drawer-overlay" onClick={onClose}><div className="drawer" role="dialog" aria-modal="true" aria-labelledby="service-drawer-title" onClick={event => event.stopPropagation()}>
    <div className="drawer-header"><h2 className="drawer-title" id="service-drawer-title">{initial ? 'Editar' : 'Novo'} item</h2><button className="icon-btn" onClick={onClose} aria-label="Fechar item"><X size={20}/></button></div>
    <div className="drawer-body">
      <label className="field-label">Nome *</label><input className="field-input" value={form.name} onChange={event => set('name', event.target.value)} placeholder="Ex: Limpeza de pele profunda"/>
      <label className="field-label">Tipo</label><select className="field-input" value={form.type} onChange={event => set('type', event.target.value as ServiceType)}>{(Object.keys(SERVICE_TYPE_LABELS) as ServiceType[]).map(type => <option key={type} value={type}>{SERVICE_TYPE_LABELS[type]}</option>)}</select>
      {form.type === 'combo' && (initial ? <ComboCompositionEditor combo={initial} services={services}/> : <div style={{ margin: '12px 0', padding: 12, borderRadius: 10, border: '1px solid #ddd6fe', background: '#faf5ff', fontSize: '.76rem', lineHeight: 1.5, color: '#6d28d9' }}><strong>Combo com várias sessões</strong><br/>Salve o combo e depois abra <strong>Editar</strong> para informar os procedimentos e a quantidade de sessões.</div>)}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 12 }}><div><label className="field-label">Preço (R$)</label><input className="field-input" inputMode="decimal" value={priceInput} onChange={event => setPriceInput(normalizeMoneyInput(event.target.value))} placeholder="0,00"/></div><div><label className="field-label">Custo (R$)</label><input className="field-input" inputMode="decimal" value={costInput} onChange={event => setCostInput(normalizeMoneyInput(event.target.value))} placeholder="0,00"/></div></div>
      <label className="field-label">Duração (minutos)</label><input className="field-input" type="number" min="0" value={form.duration_minutes ?? ''} onChange={event => set('duration_minutes', event.target.value ? Number(event.target.value) : null)} placeholder="Ex: 60"/>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(180px,1fr))', gap: 12 }}><div><label className="field-label">Retorno mínimo (dias)</label><input className="field-input" type="number" min="0" value={form.return_min_days ?? ''} onChange={event => set('return_min_days', event.target.value ? Number(event.target.value) : null)}/></div><div><label className="field-label">Retorno máximo (dias)</label><input className="field-input" type="number" min="0" value={form.return_max_days ?? ''} onChange={event => set('return_max_days', event.target.value ? Number(event.target.value) : null)}/></div></div>
      <label className="field-label">Ficha técnica</label><textarea className="field-input" rows={4} value={form.technical_sheet ?? ''} onChange={event => set('technical_sheet', event.target.value || null)} placeholder="Protocolo, ingredientes, contraindicações..."/>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 6 }}><button type="button" onClick={() => set('active', !form.active)} style={{ background: 'none', border: 0, cursor: 'pointer', color: form.active ? 'var(--primary)' : 'var(--text-3)', display: 'flex' }}>{form.active ? <ToggleRight size={28}/> : <ToggleLeft size={28}/>}</button><span>{form.active ? 'Ativo' : 'Inativo'}</span></div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}><button type="button" onClick={() => set('is_injectable', !form.is_injectable)} style={{ background: 'none', border: 0, cursor: 'pointer', color: form.is_injectable ? '#9b59b6' : 'var(--text-3)', display: 'flex' }}>{form.is_injectable ? <ToggleRight size={28}/> : <ToggleLeft size={28}/>}</button><span>{form.is_injectable ? 'Serviço injetável' : 'Não injetável'}</span></div>
      {error && <p style={{ color: 'var(--red)', fontSize: 13 }}>{error}</p>}
    </div>
    <div className="drawer-footer"><button className="btn-secondary" onClick={onClose}>Cancelar</button><button className="btn-primary" onClick={() => void handleSubmit()} disabled={saving}>{saving ? 'Salvando...' : 'Salvar'}</button></div>
  </div></div>;
}

function TemplateDrawer({ initial, onSave, onClose }: { initial?: ContractTemplate; onSave: (name: string, body: string) => Promise<void>; onClose: () => void }) {
  const [name, setName] = useState(initial?.name ?? '');
  const [body, setBody] = useState(initial?.body ?? '');
  const [guideOpen, setGuideOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const submit = async () => { if (!name.trim() || !body.trim()) { setError('Nome e texto são obrigatórios'); return; } setSaving(true); try { await onSave(name.trim(), body.trim()); onClose(); } catch (err) { setError(err instanceof Error ? err.message : 'Erro ao salvar'); } finally { setSaving(false); } };
  return <div className="drawer-overlay" onClick={onClose}><div className="drawer" onClick={event => event.stopPropagation()}><div className="drawer-header"><h2 className="drawer-title">{initial ? 'Editar' : 'Novo'} template</h2><button className="icon-btn" onClick={onClose}><X size={20}/></button></div><div className="drawer-body"><label className="field-label">Nome *</label><input className="field-input" value={name} onChange={event => setName(event.target.value)}/><label className="field-label">Texto *</label><button type="button" className="btn btn--ghost btn--sm" onClick={() => setGuideOpen(value => !value)} style={{ width: '100%', justifyContent: 'space-between', marginBottom: 8 }}>Guia de variáveis <ChevronRight size={14} style={{ transform: guideOpen ? 'rotate(90deg)' : 'none' }}/></button>{guideOpen && <div style={{ padding: 10, border: '1px solid var(--border)', borderRadius: 8, fontSize: '.8rem' }}>{'{{nome}}'}, {'{{data}}'}, {'{{servico}}'}, {'{{valor}}'}, {'{{profissional}}'}, {'{{cpf}}'}</div>}<textarea className="field-input" rows={14} value={body} onChange={event => setBody(event.target.value)}/>{error && <p style={{ color: 'var(--red)', fontSize: 13 }}>{error}</p>}</div><div className="drawer-footer"><button className="btn-secondary" onClick={onClose}>Cancelar</button><button className="btn-primary" onClick={() => void submit()} disabled={saving}>{saving ? 'Salvando...' : 'Salvar'}</button></div></div></div>;
}

function ServiceCard({ service, onEdit, onDelete, onToggle }: { service: Service; onEdit: () => void; onDelete: () => void; onToggle: () => void }) {
  const margin = service.price - service.cost_per_unit;
  return <div className="card" style={{ opacity: service.active ? 1 : .55 }}><div style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}><div style={{ flex: 1, minWidth: 0 }}><div style={{ display: 'flex', gap: 7, alignItems: 'center', flexWrap: 'wrap' }}><strong>{service.name}</strong><span style={{ ...TYPE_BADGE_STYLE[service.type], padding: '2px 8px', borderRadius: 10, fontSize: 11, fontWeight: 600 }}>{SERVICE_TYPE_LABELS[service.type]}</span></div><div style={{ display: 'flex', gap: 14, marginTop: 6, flexWrap: 'wrap', fontSize: 13, color: 'var(--text-2)' }}><span>R$ <strong style={{ color: 'var(--text)' }}>{service.price.toFixed(2)}</strong></span><span>Custo: R$ {service.cost_per_unit.toFixed(2)}</span><span style={{ color: margin >= 0 ? 'var(--green)' : 'var(--red)', fontWeight: 600 }}>Margem: R$ {margin.toFixed(2)}</span>{service.duration_minutes ? <span>⏱ {service.duration_minutes}min</span> : null}{service.return_min_days && service.return_max_days ? <span>↩ {service.return_min_days}–{service.return_max_days}d</span> : null}</div>{service.technical_sheet && <div style={{ marginTop: 8, padding: 8, background: 'var(--bg-2)', borderRadius: 8, fontSize: 12, color: 'var(--text-2)' }}>{service.technical_sheet.length > 100 ? `${service.technical_sheet.slice(0, 100)}…` : service.technical_sheet}</div>}</div><div style={{ display: 'grid', gap: 4 }}><button className="icon-btn" onClick={onToggle}>{service.active ? <ToggleRight size={20} style={{ color: 'var(--primary)' }}/> : <ToggleLeft size={20}/>}</button><button className="icon-btn" onClick={onEdit}><Pencil size={16}/></button><button className="icon-btn" onClick={onDelete} style={{ color: 'var(--red)' }}><Trash2 size={16}/></button></div></div></div>;
}

function RateInput({ value, onChange, disabled }: { value: number; onChange: (value: number) => void; disabled: boolean }) {
  return <input type="number" min="0" max="100" step="0.01" disabled={disabled} value={value} onChange={event => onChange(Number(event.target.value) || 0)} style={{ width: 80, textAlign: 'center', padding: '4px 6px', border: '1px solid var(--border)', borderRadius: 6 }}/>
}

function ConfigSection() {
  const { config: loaded, loading, saving, error, save } = useMaquininhaConfig();
  const { connected, loading: calendarLoading, connect, disconnect } = useGoogleCalendar();
  const [config, setConfig] = useState<MaquininhaConfig>(loaded);
  const [saved, setSaved] = useState(false);
  useEffect(() => setConfig(loaded), [loaded]);
  const updateBrand = (brand: 'master_visa' | 'elo', key: string, value: number) => setConfig(current => ({ ...current, rates: { ...current.rates, [brand]: { ...current.rates[brand], [key]: value } } }));
  const submit = async () => { try { await save(config); setSaved(true); window.setTimeout(() => setSaved(false), 1800); } catch { setSaved(false); } };
  return <div style={{ padding: 16 }}><div className="card"><h3 style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 15 }}><Settings size={18} style={{ color: 'var(--primary)' }}/> Taxas da maquininha</h3>{error && <p style={{ color: 'var(--red)' }}>{error}</p>}<div style={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}><thead><tr><th style={{ textAlign: 'left', padding: 8 }}>Modalidade</th><th>Master/Visa (%)</th><th>Elo (%)</th></tr></thead><tbody><tr><td style={{ padding: 8, fontWeight: 600 }}>PIX</td><td colSpan={2} style={{ textAlign: 'center' }}><RateInput disabled={loading} value={config.rates.pix} onChange={value => setConfig(current => ({ ...current, rates: { ...current.rates, pix: value } }))}/></td></tr><tr><td style={{ padding: 8, fontWeight: 600 }}>Débito</td><td style={{ textAlign: 'center' }}><RateInput disabled={loading} value={config.rates.master_visa.debito} onChange={value => updateBrand('master_visa', 'debito', value)}/></td><td style={{ textAlign: 'center' }}><RateInput disabled={loading} value={config.rates.elo.debito} onChange={value => updateBrand('elo', 'debito', value)}/></td></tr>{Array.from({ length: 18 }, (_, index) => String(index + 1)).map(inst => <tr key={inst}><td style={{ padding: 8, fontWeight: 600 }}>{inst}x</td><td style={{ textAlign: 'center' }}><RateInput disabled={loading} value={(config.rates.master_visa as Record<string, number>)[inst] ?? 0} onChange={value => updateBrand('master_visa', inst, value)}/></td><td style={{ textAlign: 'center' }}><RateInput disabled={loading} value={(config.rates.elo as Record<string, number>)[inst] ?? 0} onChange={value => updateBrand('elo', inst, value)}/></td></tr>)}</tbody></table></div><button className="btn-primary" style={{ width: '100%', marginTop: 14 }} disabled={loading || saving} onClick={() => void submit()}>{saving ? 'Salvando...' : saved ? 'Salvo!' : 'Salvar taxas'}</button></div><div className="card" style={{ marginTop: 12 }}><h3 style={{ display: 'flex', gap: 8, alignItems: 'center', marginBottom: 14 }}><Calendar size={18} style={{ color: 'var(--primary)' }}/> Integrações</h3><div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><div style={{ flex: 1 }}><strong>Google Calendar</strong><p className="page-sub">{calendarLoading ? 'Verificando...' : connected ? 'Conectado — agendamentos sincronizados automaticamente' : 'Não conectado'}</p></div>{connected ? <button className="btn btn--secondary btn--sm" disabled={calendarLoading} onClick={disconnect}><Link2Off size={15}/> Desconectar</button> : <button className="btn-primary" disabled={calendarLoading} onClick={connect}><Calendar size={15}/> Conectar</button>}</div></div></div>;
}

export function CatalogoPage() {
  const [section, setSection] = useState<Section>('servicos');
  const { servicos, loading, error, create, update, remove, toggle } = useServicos();
  const { confirm, toast } = useToast();
  const [filterType, setFilterType] = useState<ServiceType | 'todos'>('todos');
  const [search, setSearch] = useState('');
  const [sort, setSort] = useState<SortMode>('name');
  const [serviceDrawer, setServiceDrawer] = useState<{ open: boolean; item?: Service }>({ open: false });
  const [templates, setTemplates] = useState<ContractTemplate[]>([]);
  const [loadingTemplates, setLoadingTemplates] = useState(false);
  const [templatesError, setTemplatesError] = useState<string | null>(null);
  const [templateDrawer, setTemplateDrawer] = useState<{ open: boolean; item?: ContractTemplate }>({ open: false });

  const loadTemplates = useCallback(async () => { setLoadingTemplates(true); try { const result = await supabase.from('contract_templates').select('*').order('created_at', { ascending: false }); if (result.error) throw result.error; setTemplates((result.data as ContractTemplate[]) ?? []); setTemplatesError(null); } catch (err) { setTemplatesError(err instanceof Error ? err.message : 'Erro ao carregar contratos.'); } finally { setLoadingTemplates(false); } }, []);
  useEffect(() => { if (section === 'contratos') void loadTemplates(); }, [section, loadTemplates]);
  const saveTemplate = async (name: string, body: string) => { const auth = await supabase.auth.getUser(); if (templateDrawer.item) { const result = await supabase.from('contract_templates').update({ name, body }).eq('id', templateDrawer.item.id); if (result.error) throw result.error; } else { const result = await supabase.from('contract_templates').insert({ name, body, user_id: auth.data.user!.id }); if (result.error) throw result.error; } await loadTemplates(); };
  const deleteTemplate = async (id: string) => { const ok = await confirm({ title: 'Excluir template', message: 'Excluir este template?', confirmLabel: 'Excluir', tone: 'danger' }); if (!ok) return; await supabase.from('contract_templates').delete().eq('id', id); await loadTemplates(); toast.success('Template excluído.'); };
  const filtered = useMemo(() => servicos.filter(service => filterType === 'todos' || service.type === filterType).filter(service => service.name.toLowerCase().includes(search.trim().toLowerCase())).sort((a, b) => sort === 'price_desc' ? b.price - a.price : sort === 'price_asc' ? a.price - b.price : sort === 'margin_desc' ? (b.price - b.cost_per_unit) - (a.price - a.cost_per_unit) : a.name.localeCompare(b.name)), [filterType, search, servicos, sort]);
  const tabs: Array<{ key: Section; label: string; icon: ReactNode }> = [{ key: 'servicos', label: 'Serviços', icon: <BookOpen size={15}/> }, { key: 'contratos', label: 'Contratos', icon: <FileText size={15}/> }, { key: 'materiais', label: 'Materiais', icon: <Boxes size={15}/> }, { key: 'config', label: 'Config', icon: <Settings size={15}/> }];

  return <div className="page"><div className="page-header"><div><h1 className="page-title">Catálogo</h1><p className="page-sub">{servicos.filter(service => service.active).length} itens ativos</p></div>{section === 'servicos' && <button className="btn-primary" onClick={() => setServiceDrawer({ open: true })}><Plus size={18}/> Novo</button>}{section === 'contratos' && <button className="btn-primary" onClick={() => setTemplateDrawer({ open: true })}><Plus size={18}/> Novo</button>}</div>
    <div style={{ display: 'flex', gap: 4, padding: '0 16px 12px', borderBottom: '1px solid var(--border)', overflowX: 'auto' }}>{tabs.map(tab => <button key={tab.key} onClick={() => setSection(tab.key)} style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '7px 14px', borderRadius: 20, border: 0, cursor: 'pointer', whiteSpace: 'nowrap', background: section === tab.key ? 'var(--primary)' : 'var(--bg-2)', color: section === tab.key ? '#fff' : 'var(--text-2)' }}>{tab.icon}{tab.label}</button>)}</div>
    {section === 'materiais' && <MaterialsSection/>}
    {section === 'config' && <ConfigSection/>}
    {section === 'servicos' && <div style={{ padding: 16 }}><div className="search-wrap"><Search size={18} className="search-icon"/><input className="search-input" placeholder="Buscar serviço..." value={search} onChange={event => setSearch(event.target.value)}/></div><div style={{ display: 'flex', gap: 10, alignItems: 'center', marginBottom: 12, flexWrap: 'wrap' }}><span className="page-sub">{filtered.length} de {servicos.length} itens</span><select className="field-input" value={sort} onChange={event => setSort(event.target.value as SortMode)} style={{ maxWidth: 220 }}><option value="name">Nome (A-Z)</option><option value="price_desc">Preço maior</option><option value="price_asc">Preço menor</option><option value="margin_desc">Margem</option></select></div><div style={{ display: 'flex', gap: 6, marginBottom: 14, flexWrap: 'wrap' }}>{(['todos', 'servico', 'combo', 'plano', 'produto'] as const).map(type => <button key={type} onClick={() => setFilterType(type)} style={{ padding: '5px 13px', borderRadius: 16, border: '1px solid var(--border)', cursor: 'pointer', background: filterType === type ? 'var(--primary)' : 'transparent', color: filterType === type ? '#fff' : 'var(--text-2)' }}>{type === 'todos' ? 'Todos' : SERVICE_TYPE_LABELS[type]}</button>)}</div>{error ? <div className="empty-state"><p>{error}</p></div> : loading ? <div style={{ display: 'grid', gap: 10 }}>{Array.from({ length: 4 }, (_, index) => <div className="card" key={index}><Skeleton lines={2}/></div>)}</div> : filtered.length === 0 ? <div className="empty-state"><BookOpen size={48} strokeWidth={1}/><p>Nenhum item encontrado.</p></div> : <div style={{ display: 'grid', gap: 10 }}>{filtered.map(service => <ServiceCard key={service.id} service={service} onEdit={() => setServiceDrawer({ open: true, item: service })} onToggle={() => void toggle(service.id, !service.active)} onDelete={() => void (async () => { const ok = await confirm({ title: 'Excluir item', message: 'Excluir este item?', confirmLabel: 'Excluir', tone: 'danger' }); if (ok) { await remove(service.id); toast.success('Item excluído.'); } })()}/>)}</div>}</div>}
    {section === 'contratos' && <div style={{ padding: 16 }}>{templatesError ? <div className="empty-state">{templatesError}</div> : loadingTemplates ? <div className="empty-state">Carregando...</div> : templates.length === 0 ? <div className="empty-state"><FileText size={48} strokeWidth={1}/><p>Nenhum template de contrato.</p></div> : <div style={{ display: 'grid', gap: 10 }}>{templates.map(template => <div className="card" key={template.id} style={{ display: 'flex', alignItems: 'center', gap: 10 }}><FileText size={20}/><div style={{ flex: 1, minWidth: 0 }}><strong>{template.name}</strong><p className="page-sub" style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{template.body.slice(0, 90)}</p></div><button className="icon-btn" onClick={() => setTemplateDrawer({ open: true, item: template })}><Pencil size={16}/></button><button className="icon-btn" style={{ color: 'var(--red)' }} onClick={() => void deleteTemplate(template.id)}><Trash2 size={16}/></button></div>)}</div>}</div>}
    {serviceDrawer.open && <ServiceDrawer initial={serviceDrawer.item} services={servicos} onSave={serviceDrawer.item ? data => update(serviceDrawer.item!.id, data) : create} onClose={() => setServiceDrawer({ open: false })}/>} 
    {templateDrawer.open && <TemplateDrawer initial={templateDrawer.item} onSave={saveTemplate} onClose={() => setTemplateDrawer({ open: false })}/>} 
  </div>;
}
