import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { expect, test } from '@playwright/test';
import { adminClient, anonClient, signedInClient } from './helpers';

const conditions=['hipertensao','hipotensao','diabetes','cancer','problemas_cardiacos','disfuncao_renal','problemas_vasculares','epilepsia','problemas_respiratorios','problemas_tireoide','problemas_coagulacao','marcapasso','fumante','hiv_aids','hepatite'];
const history=['alergia_medicamento','alergia_frutos_mar','alergia_abelha','outras_alergias','recebeu_anestesia','cirurgias_recentes','protese_metalica','desmaios','herpes','tratamento_medico','acne','ansioso','estressado','enxaqueca','intestino_regular','menstruacao_regular','colica_menstrual'];
const habits=['leite_derivados','doces','refrigerante','fast_food','frituras','bebidas_alcoolicas','cigarros','alimentacao_especial','suplemento','atividade_fisica'];
const aesthetics=['produto_com_acido','alteracoes_recentes','limpeza_pele','microagulhamento','peeling','laser','toxina_botulinica','fios_sustentacao','preenchimento_hialuronico','bioestimulador','plastica_facial','pmma','outros_tratamentos'];
const falseMap=(keys:string[])=>Object.fromEntries(keys.map(key=>[key,false]));

async function makePatient(){const a=await signedInClient('a');const{data:{user}}=await a.auth.getUser();expect(user).toBeTruthy();const admin=adminClient();const{data,error}=await admin.from('patients').insert({user_id:user!.id,name:`E2E Anamnese v4 ${randomUUID().slice(0,8)}`}).select('id').single();expect(error).toBeNull();return{a,admin,userId:user!.id,patientId:data!.id as string};}

test('schema-4 requests are promoted to v5, accept partial answers and remove Última LP',async()=>{
 const{a,patientId}=await makePatient();
 const partial={conditions:{hipertensao:false},medications:'',medications_status:null,allergies:null,allergies_status:null,surgical_history:{},habits:{},aesthetics:{ultima_limpeza_pele:'há 2 meses',pele_paciente:'Melasma leve'}};
 const saved=await a.rpc('save_anamnesis_draft_v2',{p_patient_id:patientId,p_expected_revision:0,p_answers:partial,p_form_schema_version:4});expect(saved.error).toBeNull();
 const finalized=await a.rpc('finalize_anamnesis_v2',{p_patient_id:patientId,p_expected_revision:1,p_idempotency_key:randomUUID()});expect(finalized.error).toBeNull();const result=Array.isArray(finalized.data)?finalized.data[0]:finalized.data;expect(result?.version_id).toBeTruthy();
 const{data:version,error}=await a.from('anamnesis_versions').select('form_schema_version,answers_snapshot,form_schema_snapshot').eq('id',result!.version_id).single();expect(error).toBeNull();expect(version?.form_schema_version).toBe(5);
 const answers=version?.answers_snapshot as Record<string,unknown>;expect(answers.conditions).toEqual({hipertensao:false});expect((answers.aesthetics as Record<string,unknown>).ultima_limpeza_pele).toBeUndefined();
 const schema=version?.form_schema_snapshot as {version?:number;sections?:Array<{key?:string;fields?:Array<{key?:string}>}>};expect(schema.version).toBe(5);const skin=schema.sections?.find(section=>section.key==='skin_review');expect(skin?.fields?.some(field=>field.key==='ultima_limpeza_pele')).toBe(false);
});

test('remote-signature persistence is RLS-scoped, hash-only, cross-patient-safe and idempotent',async()=>{
 const{a,admin,userId,patientId}=await makePatient();const b=await signedInClient('b');const complete={conditions:falseMap(conditions),medications:'',medications_status:'none',allergies:null,allergies_status:null,surgical_history:{...falseMap(history),gestante:'não'},habits:falseMap(habits),aesthetics:falseMap(aesthetics)};
 const saved=await a.rpc('save_anamnesis_draft_v2',{p_patient_id:patientId,p_expected_revision:0,p_answers:complete,p_form_schema_version:4});expect(saved.error).toBeNull();const finalized=await a.rpc('finalize_anamnesis_v2',{p_patient_id:patientId,p_expected_revision:1,p_idempotency_key:randomUUID()});expect(finalized.error).toBeNull();const version=Array.isArray(finalized.data)?finalized.data[0]:finalized.data;const versionId=version!.version_id as string;
 const{data:contentHash,error:hashError}=await admin.rpc('anamnesis_version_content_sha256_v1',{p_version_id:versionId});expect(hashError).toBeNull();expect(contentHash).toMatch(/^[0-9a-f]{64}$/);
 const{data:otherPatient,error:otherPatientError}=await admin.from('patients').insert({user_id:userId,name:`E2E outra paciente ${randomUUID().slice(0,8)}`}).select('id').single();expect(otherPatientError).toBeNull();const mismatchRaw=randomBytes(32).toString('base64url');const mismatch=await admin.from('anamnesis_signature_links').insert({user_id:userId,patient_id:otherPatient!.id,anamnesis_version_id:versionId,token_hash:createHash('sha256').update(mismatchRaw).digest('hex'),content_sha256:contentHash,expires_at:new Date(Date.now()+3600000).toISOString(),created_by:userId});expect(mismatch.error).not.toBeNull();expect(mismatch.error?.message).toContain('ANAMNESIS_SIGNATURE_SCOPE_MISMATCH');
 const rawToken=randomBytes(32).toString('base64url');const tokenHash=createHash('sha256').update(rawToken).digest('hex');const{data:link,error:linkError}=await admin.from('anamnesis_signature_links').insert({user_id:userId,patient_id:patientId,anamnesis_version_id:versionId,token_hash:tokenHash,content_sha256:contentHash,expires_at:new Date(Date.now()+3600000).toISOString(),created_by:userId}).select('id,token_hash').single();expect(linkError).toBeNull();expect(link?.token_hash).toBe(tokenHash);expect(link?.token_hash).not.toContain(rawToken);
 const own=await a.from('anamnesis_signature_links').select('id').eq('id',link!.id);expect(own.data).toHaveLength(1);const cross=await b.from('anamnesis_signature_links').select('id').eq('id',link!.id);expect(cross.data).toEqual([]);const anonymous=await anonClient().from('anamnesis_signature_links').select('id').eq('id',link!.id);expect(anonymous.data).toBeNull();expect(anonymous.error).not.toBeNull();
 const denied=await a.rpc('consume_anamnesis_signature_link_v1',{p_link_id:link!.id,p_signature_path:`${userId}/anamnesis/${versionId}/signature-test.png`,p_signature_sha256:'a'.repeat(64),p_audit_metadata:{method:'e2e'}});expect(denied.error).not.toBeNull();
 const first=await admin.rpc('consume_anamnesis_signature_link_v1',{p_link_id:link!.id,p_signature_path:`${userId}/anamnesis/${versionId}/signature-test.png`,p_signature_sha256:'a'.repeat(64),p_audit_metadata:{method:'e2e'}});expect(first.error).toBeNull();const second=await admin.rpc('consume_anamnesis_signature_link_v1',{p_link_id:link!.id,p_signature_path:`${userId}/anamnesis/${versionId}/signature-test.png`,p_signature_sha256:'a'.repeat(64),p_audit_metadata:{method:'e2e-retry'}});expect(second.error).toBeNull();const one=Array.isArray(first.data)?first.data[0]:first.data;const two=Array.isArray(second.data)?second.data[0]:second.data;expect(two?.signature_id).toBe(one?.signature_id);
 const signatures=await admin.from('anamnesis_signatures').select('id').eq('anamnesis_version_id',versionId);expect(signatures.data).toHaveLength(1);
});