import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, MessageCircle, UserRound } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { buildWhatsAppUrl } from '../../lib/whatsapp';
import { proposalMoney } from '../../lib/proposals';

type OpenProposal = {
  deal_id:string; patient_id:string|null; patient_name:string|null; contact_name:string; phone:string|null;
  proposal_id:string; proposal_title:string|null; proposal_status:string; proposal_effective_status:string|null;
  proposal_total_value:number|null; proposal_sent_at:string; last_activity_at:string|null;
};
type ContactMessage={patient_id:string|null;sent_at:string|null;created_at:string};
const elapsed=(iso:string)=>{const days=Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/86400000));if(days===0)return'Hoje';if(days===1)return'1 dia';return`${days} dias`;};
const dt=(iso:string|null)=>iso?new Date(iso).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';

export function OpenProposalsPage(){
 const navigate=useNavigate();const[rows,setRows]=useState<OpenProposal[]>([]);const[contacts,setContacts]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[search,setSearch]=useState('');
 useEffect(()=>{let active=true;(async()=>{setLoading(true);setError(null);try{const{data,error:queryError}=await supabase.from('crm_pipeline_v').select('deal_id,patient_id,patient_name,contact_name,phone,proposal_id,proposal_title,proposal_status,proposal_effective_status,proposal_total_value,proposal_sent_at,last_activity_at').eq('proposal_status','issued').not('proposal_sent_at','is',null).order('proposal_sent_at',{ascending:true});if(queryError)throw queryError;const proposalRows=(data??[]).filter(row=>row.proposal_id&&row.proposal_sent_at) as OpenProposal[];const patientIds=[...new Set(proposalRows.map(row=>row.patient_id).filter(Boolean))] as string[];const lastByPatient:Record<string,string>={};if(patientIds.length){const{data:messages,error:messageError}=await supabase.from('communication_messages').select('patient_id,sent_at,created_at').in('patient_id',patientIds).order('sent_at',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false}).limit(500);if(messageError)throw messageError;for(const message of(messages??[]) as ContactMessage[]){if(message.patient_id&&!lastByPatient[message.patient_id])lastByPatient[message.patient_id]=message.sent_at??message.created_at;}}if(active){setRows(proposalRows);setContacts(lastByPatient);}}catch{if(active)setError('Não foi possível carregar as propostas em aberto.');}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return rows;return rows.filter(row=>(row.patient_name??row.contact_name).toLowerCase().includes(q)||(row.proposal_title??'').toLowerCase().includes(q));},[rows,search]);
 return <div className="page"><div className="page-header"><div><h1 className="page-title">CRM</h1><p className="page-sub">Propostas enviadas que ainda aguardam decisão</p></div></div><div className="crm-stage-segments" style={{marginBottom:12}}><Link className="btn btn--ghost btn--sm" to="/crm">Pipeline</Link><span className="btn btn--primary btn--sm" aria-current="page">Propostas em aberto</span></div><div className="card" style={{padding:12,marginBottom:12}}><input className="field-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar paciente ou proposta"/></div>{loading?<div className="card" style={{padding:16}}>Carregando propostas…</div>:error?<div className="empty-state"><p>{error}</p></div>:filtered.length===0?<div className="empty-state"><p>Nenhuma proposta enviada aguardando decisão.</p><span className="page-sub">Rascunhos e estados terminais não entram nesta visão.</span></div>:<div style={{display:'grid',gap:9}}>{filtered.map(row=>{const patientName=row.patient_name??row.contact_name;const lastContact=row.patient_id?contacts[row.patient_id]??row.last_activity_at:row.last_activity_at;return <article className="card" key={row.proposal_id} style={{padding:14,display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:12,alignItems:'center'}}><div style={{minWidth:0}}><div style={{display:'flex',gap:7,alignItems:'center',flexWrap:'wrap'}}><strong>{patientName}</strong><span className="badge badge--rose">Aguardando decisão</span>{row.proposal_effective_status==='expired'&&<span className="badge">Validade vencida</span>}</div><div className="page-sub" style={{marginTop:4}}>{row.proposal_title??'Proposta'} · enviada {dt(row.proposal_sent_at)} · <strong>{elapsed(row.proposal_sent_at)}</strong> desde o envio</div><div style={{display:'flex',gap:12,marginTop:7,fontSize:12,flexWrap:'wrap'}}><strong>{proposalMoney(row.proposal_total_value)}</strong>{lastContact&&<span className="page-sub">Último contato/atividade: {dt(lastContact)}</span>}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap',justifyContent:'flex-end'}}><button className="btn btn--primary btn--sm" onClick={()=>navigate(`/crm/deals/${row.deal_id}/proposals/${row.proposal_id}`)}>Abrir proposta <ArrowRight size={14}/></button><button className="btn btn--secondary btn--sm" disabled={!row.phone} onClick={()=>row.phone&&window.open(buildWhatsAppUrl(row.phone,`Olá ${patientName}! Tudo bem?`),'_blank','noopener,noreferrer')}><MessageCircle size={14}/> WhatsApp</button>{row.patient_id&&<button className="btn btn--ghost btn--sm" onClick={()=>navigate(`/pacientes/${row.patient_id}`)}><UserRound size={14}/> Abrir paciente</button>}</div></article>;})}</div>}</div>;
}
