import { useCallback, useEffect, useState } from 'react';
import { ChevronDown, ChevronUp, Clock3, Copy, FileCheck2, Link2, PencilLine, ShieldCheck, Unlink } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from '../../../lib/supabase';
import { createAnamnesisSignatureLink, revokeAnamnesisSignatureLink, type AnamnesisSignatureLinkRow, type AnamnesisSignatureRow } from '../../../lib/anamnesisSignature';
import type { AnamnesisCurrentRow, AnamnesisVersion } from '../../../lib/anamnesisV2';
import { useToast } from '../../../hooks/useToast';

interface Props { patientId: string; }
type SchemaField={key?:string;label?:string;type?:string;detail_key?:string}; type SchemaSection={key?:string;title?:string;fields?:SchemaField[]};
const dateTime=(value:string|null|undefined)=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';
function sectionAnswers(snapshot:Record<string,unknown>,sectionKey:string){if(sectionKey==='conditions')return(snapshot.conditions??{}) as Record<string,unknown>;if(['medical_history','womens_health','allergies'].includes(sectionKey))return(snapshot.surgical_history??{}) as Record<string,unknown>;if(['habits','food','routine'].includes(sectionKey))return(snapshot.habits??{}) as Record<string,unknown>;if(['aesthetics','procedures','skin_review'].includes(sectionKey))return(snapshot.aesthetics??{}) as Record<string,unknown>;return snapshot;}
function displayValue(snapshot:Record<string,unknown>,sectionKey:string,field:SchemaField){const key=field.key??'';const source=sectionAnswers(snapshot,sectionKey);const value=source[key];if(field.type==='status_text'){const statusKey=key==='medications'?'medications_status':'allergies_status';const status=snapshot[statusKey];if(status==='none')return key==='medications'?'Não utiliza':'Não possui';if(status==='reported')return String(snapshot[key]??'').trim()||'Informado sem descrição';return'Sem resposta registrada';}if(field.type==='text_legacy')return String(snapshot[key]??'').trim()||'Não informado no modelo legado';if(['boolean','boolean_detail','boolean_frequency','procedure_note'].includes(field.type??'')){if(value===true){if(field.detail_key){const detail=String(source[field.detail_key]??'').trim();return detail?`Sim — ${detail}`:'Sim';}return'Sim';}if(value===false){if(field.type==='procedure_note'&&field.detail_key){const detail=String(source[field.detail_key]??'').trim();if(detail)return`Não — ${detail}`;}return'Não';}return'Sem resposta registrada';}if(value===null||value===undefined||value==='')return'Não informado';return String(value);}
function HistoricalVersion({version}:{version:AnamnesisVersion}){const sections=((version.form_schema_snapshot.sections??[]) as SchemaSection[]).filter(s=>Array.isArray(s.fields));return <div style={{display:'grid',gap:12,marginTop:12}}><div className="page-sub">Documento somente leitura · schema {version.form_schema_version}{version.migration_source==='legacy'?' · migrado do modelo anterior':''}</div>{sections.map((section,index)=><div className="card" key={`${section.key??index}`} style={{padding:12}}><strong style={{display:'block',marginBottom:8}}>{section.title??'Seção'}</strong><div style={{display:'grid',gap:6}}>{(section.fields??[]).map((field,i)=><div key={`${field.key??i}`} style={{display:'grid',gridTemplateColumns:'minmax(150px,.8fr) minmax(0,1.2fr)',gap:10,borderBottom:'1px solid var(--border)',paddingBottom:6}}><span className="page-sub">{field.label??field.key}</span><span style={{fontSize:13,whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{displayValue(version.answers_snapshot,section.key??'',field)}</span></div>)}</div></div>)}</div>;}

export function AnamneseTab({patientId}:Props){
 const navigate=useNavigate();const[searchParams]=useSearchParams();const{toast,confirm}=useToast();
 const[current,setCurrent]=useState<AnamnesisCurrentRow|null>(null);const[versions,setVersions]=useState<AnamnesisVersion[]>([]);const[links,setLinks]=useState<AnamnesisSignatureLinkRow[]>([]);const[signatures,setSignatures]=useState<AnamnesisSignatureRow[]>([]);const[selectedVersionId,setSelectedVersionId]=useState<string|null>(null);const[generatedUrl,setGeneratedUrl]=useState<string|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[actionBusy,setActionBusy]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const[currentResult,versionsResult,linksResult,signaturesResult]=await Promise.all([supabase.from('anamnesis').select('*').eq('patient_id',patientId).maybeSingle(),supabase.from('anamnesis_versions').select('id,anamnesis_id,user_id,patient_id,version_number,form_schema_version,answers_snapshot,form_schema_snapshot,completed_at,author_user_id,source_type,migration_source,supersedes_version_id,created_at').eq('patient_id',patientId).order('version_number',{ascending:false}),supabase.from('anamnesis_signature_links').select('id,user_id,patient_id,anamnesis_version_id,expires_at,revoked_at,consumed_at,created_at').eq('patient_id',patientId).order('created_at',{ascending:false}),supabase.from('anamnesis_signatures').select('id,anamnesis_version_id,signed_at').eq('patient_id',patientId).order('signed_at',{ascending:false})]);if(currentResult.error)throw currentResult.error;if(versionsResult.error)throw versionsResult.error;if(linksResult.error)throw linksResult.error;if(signaturesResult.error)throw signaturesResult.error;const nextCurrent=(currentResult.data??null) as AnamnesisCurrentRow|null;const nextVersions=(versionsResult.data??[]) as AnamnesisVersion[];setCurrent(nextCurrent);setVersions(nextVersions);setLinks((linksResult.data??[]) as AnamnesisSignatureLinkRow[]);setSignatures((signaturesResult.data??[]) as AnamnesisSignatureRow[]);const requested=Number(searchParams.get('version')??0);setSelectedVersionId(nextVersions.find(v=>v.version_number===requested)?.id??null);}catch{setError('Não foi possível carregar a anamnese.');}finally{setLoading(false);}},[patientId,searchParams]);
 useEffect(()=>{void load();},[load]);
 const latest=versions[0]??null;const latestSignature=latest?signatures.find(s=>s.anamnesis_version_id===latest.id)??null:null;const activeLink=latest?links.find(l=>l.anamnesis_version_id===latest.id&&!l.revoked_at&&!l.consumed_at&&new Date(l.expires_at).getTime()>Date.now())??null:null;
 const state=current?.status==='draft'?'Draft':latestSignature?'Assinada':activeLink?'Aguardando assinatura':latest?'Finalizada':'Sem anamnese';
 const generate=async()=>{if(!latest||actionBusy)return;setActionBusy(true);setGeneratedUrl(null);try{const result=await createAnamnesisSignatureLink(latest.id);const url=`${window.location.origin}/assinar/anamnese/${result.token}`;setGeneratedUrl(url);toast.success('Link seguro gerado. Ele só pode ser recuperado agora; copie antes de sair.');await load();}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível gerar o link.');}finally{setActionBusy(false);}};
 const copy=async()=>{if(!generatedUrl)return;try{await navigator.clipboard.writeText(generatedUrl);toast.success('Link copiado.');}catch{toast.error('Não foi possível copiar automaticamente.');}};
 const revoke=async()=>{if(!activeLink||actionBusy)return;const ok=await confirm({title:'Revogar link de assinatura?',message:'A paciente não poderá mais usar este link. Você poderá gerar outro depois.',confirmLabel:'Revogar',cancelLabel:'Manter',tone:'warning'});if(!ok)return;setActionBusy(true);try{await revokeAnamnesisSignatureLink(activeLink.id);setGeneratedUrl(null);toast.success('Link revogado.');await load();}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível revogar o link.');}finally{setActionBusy(false);}};
 if(loading)return<div className="loading-state">Carregando...</div>;if(error)return<div className="empty-state"><p>{error}</p></div>;
 return <div style={{padding:18,display:'grid',gap:12}}>
  <div className="card" style={{padding:14}}><div style={{display:'flex',alignItems:'flex-start',gap:10,flexWrap:'wrap'}}><div style={{flex:1,minWidth:220}}><div style={{display:'flex',alignItems:'center',gap:7}}><FileCheck2 size={17}/><strong>Anamnese atual</strong><span className={`badge ${state==='Assinada'?'badge--green':state==='Draft'?'badge--rose':''}`}>{state}</span></div>{latest?<div className="page-sub" style={{marginTop:6}}>Versão {latest.version_number} · concluída em {dateTime(latest.completed_at)}</div>:<div className="page-sub" style={{marginTop:6}}>Nenhuma versão concluída.</div>}{current?.status==='draft'&&<div style={{display:'flex',alignItems:'center',gap:6,marginTop:8,fontSize:13}}><Clock3 size={14}/><strong>Anamnese pendente / rascunho</strong><span className="page-sub">· salva {dateTime(current.last_saved_at)}</span></div>}{latestSignature&&<div style={{display:'flex',gap:6,alignItems:'center',marginTop:8,fontSize:13}}><ShieldCheck size={14}/><strong>Assinada</strong><span className="page-sub">· {dateTime(latestSignature.signed_at)}</span></div>}{activeLink&&<div className="page-sub" style={{marginTop:7}}>Link ativo até {dateTime(activeLink.expires_at)}. O token não fica armazenado em texto aberto no Hub.</div>}</div><button className="btn btn--primary btn--sm" type="button" onClick={()=>navigate(`/pacientes/${patientId}/anamnese`)}><PencilLine size={15}/>{current?.status==='draft'?'Continuar':latest?'Atualizar anamnese':'Preencher anamnese'}</button></div>
   {latest&&<div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:12,paddingTop:12,borderTop:'1px solid var(--border)'}}>{!latestSignature&&!activeLink&&<button className="btn btn--secondary btn--sm" disabled={actionBusy} onClick={()=>void generate()}><Link2 size={14}/> Gerar link</button>}{generatedUrl&&<button className="btn btn--primary btn--sm" onClick={()=>void copy()}><Copy size={14}/> Copiar link</button>}{activeLink&&<button className="btn btn--ghost btn--sm" disabled={actionBusy} onClick={()=>void revoke()}><Unlink size={14}/> Revogar link</button>}</div>}
  </div>
  <div className="card" style={{padding:14}}><strong>Histórico</strong>{versions.length===0?<p className="page-sub" style={{marginTop:8}}>Nenhuma versão concluída ainda.</p>:<div style={{display:'grid',gap:7,marginTop:10}}>{versions.map(version=>{const open=selectedVersionId===version.id;const signed=signatures.some(s=>s.anamnesis_version_id===version.id);return <div key={version.id} style={{border:'1px solid var(--border)',borderRadius:9,overflow:'hidden'}}><button type="button" onClick={()=>setSelectedVersionId(open?null:version.id)} style={{width:'100%',minHeight:48,display:'flex',alignItems:'center',gap:8,padding:'9px 11px',border:0,background:'var(--bg-2)',color:'var(--text)',textAlign:'left',cursor:'pointer'}}><div style={{flex:1}}><strong>Versão {version.version_number}</strong><div className="page-sub">{dateTime(version.completed_at)}{version.migration_source==='legacy'?' · legado preservado':''}{signed?' · assinada':''}</div></div>{open?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button>{open&&<div style={{padding:'0 10px 10px'}}><HistoricalVersion version={version}/></div>}</div>;})}</div>}</div>
 </div>;
}
