import { createBrowserRouter, createRoutesFromElements, Navigate, Route, RouterProvider } from 'react-router-dom';
import { lazy, Suspense, type ReactNode } from 'react';
import { useAuth } from './hooks/useAuth';
import { DirtySurface } from './components/layout/DirtySurface';

const Layout=lazy(()=>import('./components/layout/Layout').then(m=>({default:m.Layout})));const LoginPage=lazy(()=>import('./pages/auth/LoginPage').then(m=>({default:m.LoginPage})));const AnamnesisSignaturePage=lazy(()=>import('./pages/public/AnamnesisSignaturePage').then(m=>({default:m.AnamnesisSignaturePage})));const AgendaPage=lazy(()=>import('./pages/agenda/AgendaPage').then(m=>({default:m.AgendaV2Page})));const DashboardPage=lazy(()=>import('./pages/dashboard/DashboardPage').then(m=>({default:m.DashboardPage})));const CommunicationPage=lazy(()=>import('./pages/comunicacao/CommunicationPage').then(m=>({default:m.CommunicationPage})));const RelationshipPage=lazy(()=>import('./pages/relacionamento/RelationshipPage').then(m=>({default:m.RelationshipPage})));const CrmPage=lazy(()=>import('./pages/crm/CrmPage').then(m=>({default:m.CrmPage})));const OpenProposalsPage=lazy(()=>import('./pages/crm/OpenProposalsPage').then(m=>({default:m.OpenProposalsPage})));const ProposalEditorPage=lazy(()=>import('./pages/crm/ProposalEditorPage').then(m=>({default:m.ProposalEditorPage})));const PacientesPage=lazy(()=>import('./pages/pacientes/PacientesPage').then(m=>({default:m.PacientesPage})));const AnamneseEditorPage=lazy(()=>import('./pages/pacientes/AnamneseEditorPage').then(m=>({default:m.AnamneseEditorPage})));const RegistrarPage=lazy(()=>import('./pages/registrar/RegistrarPage').then(m=>({default:m.RegistrarPage})));const AttendanceModePage=lazy(()=>import('./pages/atendimento/AttendanceModePage').then(m=>({default:m.AttendanceModePage})));const FinanceiroPage=lazy(()=>import('./pages/financeiro/FinanceiroPage').then(m=>({default:m.FinanceiroPage})));const CatalogoPage=lazy(()=>import('./pages/catalogo/CatalogoPage').then(m=>({default:m.CatalogoPage})));const ServiceReturnSettingsPage=lazy(()=>import('./pages/catalogo/ServiceReturnSettingsPage').then(m=>({default:m.ServiceReturnSettingsPage})));const RetornosHubPage=lazy(()=>import('./pages/retornos/RetornosHubPage').then(m=>({default:m.RetornosHubPage})));const PacotesPage=lazy(()=>import('./pages/pacotes/PacotesPage').then(m=>({default:m.PacotesPage})));const HubHealthPage=lazy(()=>import('./pages/saude/HubHealthPage').then(m=>({default:m.HubHealthPage})));
function ProtectedRoute({children}:{children:ReactNode}){const{user,loading}=useAuth();if(loading)return<div className="route-loader"><span className="skeleton route-loader__bar"/></div>;if(!user)return<Navigate to="/login" replace/>;return<>{children}</>;}function RouteErrorPage(){return<div className="route-error"><strong>Algo deu errado.</strong><p>Esta tela não pôde ser carregada.</p><button className="btn btn--primary btn--md" onClick={()=>window.location.reload()}>Tentar novamente</button></div>;}
const router=createBrowserRouter(createRoutesFromElements(<Route errorElement={<RouteErrorPage/>}><Route path="/login" element={<LoginPage/>}/><Route path="/assinar/anamnese/:token" element={<AnamnesisSignaturePage/>}/><Route path="/" element={<ProtectedRoute><Layout/></ProtectedRoute>}><Route index element={<Navigate to="/dashboard" replace/>}/><Route path="dashboard" element={<DashboardPage/>}/><Route path="comunicacao" element={<CommunicationPage/>}/><Route path="relacionamento" element={<RelationshipPage/>}/><Route path="agenda" element={<AgendaPage/>}/><Route path="retornos" element={<RetornosHubPage/>}/><Route path="crm" element={<CrmPage/>}/><Route path="crm/propostas-em-aberto" element={<OpenProposalsPage/>}/><Route path="crm/deals/:dealId/proposals/:proposalId" element={<ProposalEditorPage/>}/><Route path="pacientes" element={<PacientesPage/>}/><Route path="pacientes/:patientId" element={<PacientesPage/>}/><Route path="pacientes/:patientId/anamnese" element={<DirtySurface id="anamnesis" cleanWhenText="Salvo às"><AnamneseEditorPage/></DirtySurface>}/><Route path="atendimento/:appointmentId" element={<AttendanceModePage/>}/><Route path="registrar" element={<DirtySurface id="registrar" cleanWhenText="Atendimento registrado!"><RegistrarPage/></DirtySurface>}/><Route path="financeiro" element={<FinanceiroPage/>}/><Route path="pacotes" element={<PacotesPage/>}/><Route path="catalogo" element={<CatalogoPage/>}/><Route path="catalogo/acompanhamentos" element={<ServiceReturnSettingsPage/>}/><Route path="saude" element={<HubHealthPage/>}/></Route><Route path="*" element={<Navigate to="/dashboard" replace/>}/></Route>));
export default function AppRoutesV2(){return<Suspense fallback={<div className="route-loader"><span className="skeleton route-loader__bar"/></div>}><RouterProvider router={router}/></Suspense>;}
