-- Reconcile table grants to the audited production privilege matrix.
-- DDL only; no row data is modified.

revoke all privileges on table
  public.anamnesis,
  public.anamnesis_versions,
  public.appointments,
  public.communication_attention_state,
  public.communication_messages,
  public.communication_preferences,
  public.communication_templates,
  public.contacts,
  public.contract_template_versions,
  public.contract_templates,
  public.contracts,
  public.crm_activities,
  public.crm_deal_interests,
  public.crm_followups,
  public.data_quality_issue_suppressions,
  public.deals,
  public.google_calendar_connections,
  public.google_calendar_tokens,
  public.injectable_application_points,
  public.injectable_applications,
  public.injectable_maps,
  public.injectable_product_lots,
  public.injectable_products,
  public.maquininha_configs,
  public.oauth_states,
  public.package_payments,
  public.package_redemptions,
  public.patient_credit_ledger,
  public.patient_notes,
  public.patient_package_items,
  public.patient_packages,
  public.patient_photo_sessions,
  public.patient_photos,
  public.patients,
  public.pix_installments,
  public.procedure_followup_plans,
  public.procedure_followup_tasks,
  public.procedure_items,
  public.procedure_payments,
  public.procedure_returns,
  public.procedures,
  public.professional_profiles,
  public.relationship_preferences,
  public.service_aftercare_protocol_steps,
  public.service_aftercare_protocols,
  public.services,
  public.treatment_proposal_items,
  public.treatment_proposal_versions,
  public.treatment_proposals,
  public.vouchers
from anon, authenticated;

grant all privileges on table
  public.anamnesis,
  public.anamnesis_versions,
  public.appointments,
  public.communication_attention_state,
  public.communication_messages,
  public.communication_preferences,
  public.communication_templates,
  public.contacts,
  public.contract_template_versions,
  public.contract_templates,
  public.contracts,
  public.crm_activities,
  public.crm_deal_interests,
  public.crm_followups,
  public.data_quality_issue_suppressions,
  public.deals,
  public.google_calendar_connections,
  public.google_calendar_tokens,
  public.injectable_application_points,
  public.injectable_applications,
  public.injectable_maps,
  public.injectable_product_lots,
  public.injectable_products,
  public.maquininha_configs,
  public.oauth_states,
  public.package_payments,
  public.package_redemptions,
  public.patient_credit_ledger,
  public.patient_notes,
  public.patient_package_items,
  public.patient_packages,
  public.patient_photo_sessions,
  public.patient_photos,
  public.patients,
  public.pix_installments,
  public.procedure_followup_plans,
  public.procedure_followup_tasks,
  public.procedure_items,
  public.procedure_payments,
  public.procedure_returns,
  public.procedures,
  public.professional_profiles,
  public.relationship_preferences,
  public.service_aftercare_protocol_steps,
  public.service_aftercare_protocols,
  public.services,
  public.treatment_proposal_items,
  public.treatment_proposal_versions,
  public.treatment_proposals,
  public.vouchers
to service_role;

grant SELECT, INSERT, UPDATE on table
  public.anamnesis,
  public.contacts,
  public.deals,
  public.patient_photo_sessions,
  public.patient_photos
to authenticated;

grant SELECT on table
  public.anamnesis_versions,
  public.communication_messages,
  public.contract_template_versions,
  public.contract_templates,
  public.package_payments,
  public.package_redemptions,
  public.patient_credit_ledger,
  public.patient_package_items,
  public.patient_packages,
  public.procedure_followup_plans,
  public.procedure_followup_tasks,
  public.professional_profiles,
  public.treatment_proposal_items,
  public.treatment_proposal_versions,
  public.treatment_proposals,
  public.vouchers
to authenticated;

grant SELECT, INSERT, UPDATE, DELETE on table
  public.appointments,
  public.communication_attention_state,
  public.communication_preferences,
  public.communication_templates,
  public.contracts,
  public.crm_activities,
  public.crm_deal_interests,
  public.crm_followups,
  public.data_quality_issue_suppressions,
  public.injectable_application_points,
  public.injectable_applications,
  public.injectable_maps,
  public.injectable_product_lots,
  public.injectable_products,
  public.maquininha_configs,
  public.patient_notes,
  public.patients,
  public.pix_installments,
  public.procedure_payments,
  public.procedures,
  public.relationship_preferences,
  public.service_aftercare_protocol_steps,
  public.service_aftercare_protocols,
  public.services
to authenticated;

grant DELETE on table
  public.google_calendar_tokens
to authenticated;

grant SELECT, INSERT on table
  public.procedure_items
to authenticated;
