-- Hub Giulia 3.2 — atomic procedure coverage and redemption.

alter table public.procedures add column gross_value numeric(14,2);
alter table public.procedures add column covered_value numeric(14,2);
update public.procedures set gross_value=round(total_value,2), covered_value=0 where gross_value is null or covered_value is null;
alter table public.procedures alter column gross_value set default 0, alter column gross_value set not null, alter column covered_value set default 0, alter column covered_value set not null;
alter table public.procedures add constraint procedures_coverage_values_check check (gross_value>=0 and covered_value>=0 and covered_value<=gross_value and abs(total_value-(gross_value-covered_value))<=0.02);
alter table public.procedures drop constraint procedures_payment_method_check;
alter table public.procedures add constraint procedures_payment_method_check check (payment_method in ('dinheiro','cartao_credito','cartao_debito','pix','pix_parcelado','split','package_credit'));

alter table public.procedure_items add column coverage_value_snapshot numeric(14,2);
alter table public.procedure_items add column amount_due_snapshot numeric(14,2);
update public.procedure_items set coverage_value_snapshot=0, amount_due_snapshot=round(final_price,2) where coverage_value_snapshot is null or amount_due_snapshot is null;
alter table public.procedure_items alter column coverage_value_snapshot set default 0, alter column coverage_value_snapshot set not null, alter column amount_due_snapshot set default 0, alter column amount_due_snapshot set not null;
alter table public.procedure_items add constraint procedure_items_coverage_check check (coverage_value_snapshot>=0 and coverage_value_snapshot<=final_price and amount_due_snapshot>=0 and abs(amount_due_snapshot-(final_price-coverage_value_snapshot))<=0.02);

create or replace function public.create_procedure_v3(
  p_idempotency_key uuid,p_patient_id uuid,p_appointment_id uuid,p_performed_at timestamptz,p_items jsonb,p_payment_entries jsonb,p_injectable_maps jsonb,p_coverages jsonb,p_notes text
) returns public.procedures language plpgsql security invoker set search_path=public,pg_temp as $$
declare
 v_user_id uuid:=auth.uid(); v_proc public.procedures; v_existing public.procedures; v_payload_hash text; v_item_count integer; v_owned_count integer; v_coverage_count integer; v_gross numeric(14,2):=0; v_covered numeric(14,2):=0; v_due numeric(14,2):=0; v_total_cost numeric(14,2):=0; v_allocated numeric(14,2):=0; v_payment_count integer:=0; v_immediate_net numeric(14,2):=0; v_fee_total numeric(14,2):=0; v_payment_method text; v_appointment_patient uuid; v_appointment_status text; v_lock_id uuid; v_cov record; v_package public.patient_packages; v_package_item public.patient_package_items; v_balance numeric(12,3); v_procedure_item public.procedure_items; v_ledger public.patient_credit_ledger;
begin
 p_injectable_maps:=coalesce(p_injectable_maps,'[]'::jsonb); p_coverages:=coalesce(p_coverages,'[]'::jsonb); p_payment_entries:=coalesce(p_payment_entries,'[]'::jsonb);
 if jsonb_typeof(p_coverages)<>'array' then raise exception using errcode='22023',message='ATTENDANCE_COVERAGES_INVALID'; end if;
 if jsonb_array_length(p_coverages)=0 then return public.create_procedure_v2(p_idempotency_key,p_patient_id,p_appointment_id,p_performed_at,p_items,p_payment_entries,p_injectable_maps,p_notes); end if;
 if v_user_id is null then raise exception using errcode='P0001',message='ATTENDANCE_SESSION_REQUIRED'; end if; if p_idempotency_key is null then raise exception using errcode='22023',message='ATTENDANCE_IDEMPOTENCY_KEY_REQUIRED'; end if; if p_patient_id is null then raise exception using errcode='22023',message='ATTENDANCE_PATIENT_REQUIRED'; end if; if p_performed_at is null then raise exception using errcode='22023',message='ATTENDANCE_PERFORMED_AT_REQUIRED'; end if;
 if jsonb_typeof(coalesce(p_items,'null'::jsonb))<>'array' or jsonb_array_length(p_items)=0 then raise exception using errcode='22023',message='ATTENDANCE_ITEMS_REQUIRED'; end if; if jsonb_typeof(p_payment_entries)<>'array' then raise exception using errcode='22023',message='ATTENDANCE_PAYMENTS_INVALID'; end if; if jsonb_typeof(p_injectable_maps)<>'array' then raise exception using errcode='22023',message='ATTENDANCE_INJECTABLE_MAPS_INVALID'; end if;
 v_payload_hash:=md5(jsonb_build_object('v',3,'patient_id',p_patient_id,'appointment_id',p_appointment_id,'performed_at',p_performed_at,'items',p_items,'payment_entries',p_payment_entries,'injectable_maps',p_injectable_maps,'coverages',p_coverages,'notes',p_notes)::text);
 select * into v_existing from public.procedures where user_id=v_user_id and idempotency_key=p_idempotency_key; if found then if v_existing.idempotency_payload_hash<>v_payload_hash then raise exception using errcode='P0001',message='ATTENDANCE_IDEMPOTENCY_CONFLICT'; end if; return v_existing; end if;
 perform 1 from public.patients where id=p_patient_id and user_id=v_user_id; if not found then raise exception using errcode='P0001',message='ATTENDANCE_PATIENT_FORBIDDEN'; end if;
 if p_appointment_id is not null then select patient_id,status into v_appointment_patient,v_appointment_status from public.appointments where id=p_appointment_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='ATTENDANCE_APPOINTMENT_FORBIDDEN'; end if; if v_appointment_patient<>p_patient_id then raise exception using errcode='P0001',message='ATTENDANCE_APPOINTMENT_PATIENT_MISMATCH'; end if; select * into v_existing from public.procedures where user_id=v_user_id and idempotency_key=p_idempotency_key; if found then if v_existing.idempotency_payload_hash<>v_payload_hash then raise exception using errcode='P0001',message='ATTENDANCE_IDEMPOTENCY_CONFLICT'; end if; return v_existing; end if; if exists(select 1 from public.procedures where user_id=v_user_id and appointment_id=p_appointment_id) then raise exception using errcode='P0001',message='ATTENDANCE_APPOINTMENT_ALREADY_COMPLETED'; end if; if v_appointment_status='cancelado' then raise exception using errcode='P0001',message='ATTENDANCE_APPOINTMENT_CANCELLED'; end if; end if;
 if exists(select 1 from jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric) where i.service_id is null or coalesce(i.qty,1)<=0 or i.final_price is null or i.final_price<0) then raise exception using errcode='22023',message='ATTENDANCE_ITEM_INVALID'; end if;
 select count(*) into v_item_count from jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric); if (select count(distinct i.service_id) from jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric))<>v_item_count then raise exception using errcode='22023',message='ATTENDANCE_DUPLICATE_SERVICE_ITEM'; end if; select count(*) into v_owned_count from public.services s join jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric) on i.service_id=s.id where s.user_id=v_user_id; if v_owned_count<>v_item_count then raise exception using errcode='P0001',message='ATTENDANCE_SERVICE_FORBIDDEN'; end if;
 if exists(select 1 from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric) where c.service_id is null or c.package_item_id is null or coalesce(c.quantity,0)<=0) then raise exception using errcode='22023',message='ATTENDANCE_COVERAGE_INVALID'; end if; select count(*) into v_coverage_count from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric); if (select count(distinct c.service_id) from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric))<>v_coverage_count then raise exception using errcode='22023',message='ATTENDANCE_DUPLICATE_COVERAGE_SERVICE'; end if;
 if exists(select 1 from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric) left join jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric) on i.service_id=c.service_id where i.service_id is null or c.quantity>i.qty) then raise exception using errcode='22023',message='ATTENDANCE_COVERAGE_QUANTITY_INVALID'; end if;
 for v_lock_id in select distinct c.package_item_id from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric) order by c.package_item_id loop perform 1 from public.patient_package_items where id=v_lock_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='ATTENDANCE_PACKAGE_ITEM_FORBIDDEN'; end if; end loop;
 for v_cov in select * from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric) loop select i.* into v_package_item from public.patient_package_items i where i.id=v_cov.package_item_id and i.user_id=v_user_id; select p.* into v_package from public.patient_packages p where p.id=v_package_item.package_id and p.user_id=v_user_id for update; if not found or v_package.patient_id<>p_patient_id then raise exception using errcode='P0001',message='ATTENDANCE_PACKAGE_PATIENT_MISMATCH'; end if; if v_package.status<>'active' then raise exception using errcode='P0001',message='ATTENDANCE_PACKAGE_NOT_ACTIVE'; end if; if v_package.valid_from is not null and v_package.valid_from>current_date then raise exception using errcode='P0001',message='ATTENDANCE_PACKAGE_NOT_STARTED'; end if; if v_package.valid_until is not null and v_package.valid_until<current_date then raise exception using errcode='P0001',message='ATTENDANCE_PACKAGE_EXPIRED'; end if; if v_package_item.service_id is null or v_package_item.service_id<>v_cov.service_id then raise exception using errcode='P0001',message='ATTENDANCE_PACKAGE_SERVICE_MISMATCH'; end if; select coalesce(sum(quantity_delta),0)::numeric(12,3) into v_balance from public.patient_credit_ledger where package_item_id=v_package_item.id and user_id=v_user_id; if v_balance<v_cov.quantity then raise exception using errcode='P0001',message='ATTENDANCE_PACKAGE_INSUFFICIENT_BALANCE'; end if; end loop;
 select round(coalesce(sum(i.final_price),0),2),round(coalesce(sum(s.cost_per_unit*coalesce(i.qty,1)),0),2) into v_gross,v_total_cost from jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric) join public.services s on s.id=i.service_id and s.user_id=v_user_id;
 select round(coalesce(sum(round(i.final_price*c.quantity/i.qty,2)),0),2) into v_covered from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric) join jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric) on i.service_id=c.service_id; v_due:=round(v_gross-v_covered,2); if v_due<0 then raise exception using errcode='22023',message='ATTENDANCE_COVERAGE_EXCEEDS_VALUE'; end if;
 if v_due=0 then if jsonb_array_length(p_payment_entries)<>0 then raise exception using errcode='22023',message='ATTENDANCE_COVERED_PAYMENT_NOT_ALLOWED'; end if; v_payment_method:='package_credit'; v_immediate_net:=0; v_fee_total:=0; else if jsonb_array_length(p_payment_entries)=0 then raise exception using errcode='22023',message='ATTENDANCE_PAYMENTS_REQUIRED'; end if; if exists(select 1 from jsonb_to_recordset(p_payment_entries) as pay(method text,base_amount numeric,amount numeric,card_brand text,installments integer,fee_pct numeric,fee_value numeric,net_amount numeric,absorve_taxa boolean,scheduled_date date) where pay.method not in ('dinheiro','pix','cartao_credito','cartao_debito') or pay.base_amount is null or pay.base_amount<0 or pay.amount is null or pay.amount<0 or pay.net_amount is null or pay.net_amount<0 or coalesce(pay.installments,1)<1 or (pay.fee_pct is not null and (pay.fee_pct<0 or pay.fee_pct>100)) or (pay.fee_value is not null and pay.fee_value<0) or abs(pay.amount-coalesce(pay.fee_value,0)-pay.net_amount)>0.02 or (pay.method in ('cartao_credito','cartao_debito') and pay.card_brand not in ('master_visa','elo')) or (pay.method not in ('cartao_credito','cartao_debito') and pay.card_brand is not null) or (pay.method<>'cartao_credito' and coalesce(pay.installments,1)<>1)) then raise exception using errcode='22023',message='ATTENDANCE_PAYMENT_INVALID'; end if; select count(*),round(coalesce(sum(pay.base_amount),0),2),round(coalesce(sum(case when pay.scheduled_date is null or pay.scheduled_date<=current_date then pay.net_amount else 0 end),0),2),round(coalesce(sum(coalesce(pay.fee_value,0)),0),2) into v_payment_count,v_allocated,v_immediate_net,v_fee_total from jsonb_to_recordset(p_payment_entries) as pay(method text,base_amount numeric,amount numeric,card_brand text,installments integer,fee_pct numeric,fee_value numeric,net_amount numeric,absorve_taxa boolean,scheduled_date date); if v_payment_count<1 then raise exception using errcode='22023',message='ATTENDANCE_PAYMENTS_REQUIRED'; end if; if abs(v_allocated-v_due)>0.02 then raise exception using errcode='22023',message='ATTENDANCE_PAYMENT_TOTAL_MISMATCH'; end if; v_payment_method:='split'; end if;
 if exists(select 1 from jsonb_array_elements(p_injectable_maps) as m(value) where jsonb_typeof(m.value)<>'object' or jsonb_typeof(m.value->'points')<>'array') then raise exception using errcode='22023',message='ATTENDANCE_INJECTABLE_MAP_INVALID'; end if; if exists(select 1 from jsonb_array_elements(p_injectable_maps) as m(value) cross join lateral jsonb_array_elements(m.value->'points') as pt(value) where nullif(pt.value->>'service_id','') is null or not exists(select 1 from jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric) where i.service_id::text=pt.value->>'service_id')) then raise exception using errcode='22023',message='ATTENDANCE_INJECTABLE_SERVICE_MISMATCH'; end if;
 begin insert into public.procedures(user_id,patient_id,appointment_id,performed_at,services_ids,total_value,gross_value,covered_value,total_cost,payment_method,card_fee_pct,card_fee_value,net_value,notes,idempotency_key,idempotency_payload_hash) values(v_user_id,p_patient_id,p_appointment_id,p_performed_at,'[]'::jsonb,v_due,v_gross,v_covered,v_total_cost,v_payment_method,null,nullif(v_fee_total,0),v_immediate_net,p_notes,p_idempotency_key,v_payload_hash) returning * into v_proc; exception when unique_violation then select * into v_existing from public.procedures where user_id=v_user_id and idempotency_key=p_idempotency_key; if found then if v_existing.idempotency_payload_hash<>v_payload_hash then raise exception using errcode='P0001',message='ATTENDANCE_IDEMPOTENCY_CONFLICT'; end if; return v_existing; end if; raise; end;
 insert into public.procedure_items(procedure_id,user_id,service_id,name,qty,list_price,final_price,discount,cost_snapshot,coverage_value_snapshot,amount_due_snapshot) select v_proc.id,v_user_id,s.id,s.name,coalesce(i.qty,1),s.price,i.final_price,greatest((s.price*coalesce(i.qty,1))-i.final_price,0),s.cost_per_unit,coalesce((select round(i.final_price*c.quantity/i.qty,2) from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric) where c.service_id=i.service_id),0),i.final_price-coalesce((select round(i.final_price*c.quantity/i.qty,2) from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric) where c.service_id=i.service_id),0) from jsonb_to_recordset(p_items) as i(service_id uuid,qty numeric,final_price numeric) join public.services s on s.id=i.service_id and s.user_id=v_user_id;
 update public.procedures set services_ids=(select coalesce(jsonb_agg(e.value->'service_id' order by e.ordinality),'[]'::jsonb) from jsonb_array_elements(p_items) with ordinality as e(value,ordinality)) where id=v_proc.id and user_id=v_user_id;
 if v_due>0 then insert into public.procedure_payments(procedure_id,user_id,method,amount,card_brand,installments,fee_pct,fee_value,net_amount,absorve_taxa,scheduled_date,paid_at) select v_proc.id,v_user_id,pay.method,pay.amount,pay.card_brand,coalesce(pay.installments,1),pay.fee_pct,pay.fee_value,pay.net_amount,coalesce(pay.absorve_taxa,true),pay.scheduled_date,case when pay.scheduled_date is null or pay.scheduled_date<=current_date then now() else null end from jsonb_to_recordset(p_payment_entries) as pay(method text,base_amount numeric,amount numeric,card_brand text,installments integer,fee_pct numeric,fee_value numeric,net_amount numeric,absorve_taxa boolean,scheduled_date date); end if;
 for v_cov in select * from jsonb_to_recordset(p_coverages) as c(service_id uuid,package_item_id uuid,quantity numeric) loop select pi.* into v_procedure_item from public.procedure_items pi where pi.procedure_id=v_proc.id and pi.user_id=v_user_id and pi.service_id=v_cov.service_id; select i.* into v_package_item from public.patient_package_items i where i.id=v_cov.package_item_id and i.user_id=v_user_id; select p.* into v_package from public.patient_packages p where p.id=v_package_item.package_id and p.user_id=v_user_id; insert into public.patient_credit_ledger(user_id,patient_id,package_id,package_item_id,movement_type,quantity_delta,source_type,source_id,procedure_id,procedure_item_id,procedure_id_snapshot,procedure_item_id_snapshot,reason,idempotency_key,created_by) values(v_user_id,p_patient_id,v_package.id,v_package_item.id,'redeem',-round(v_cov.quantity,3),'procedure_redemption',v_proc.id,v_proc.id,v_procedure_item.id,v_proc.id,v_procedure_item.id,'Atendimento coberto por pacote','redeem:'||v_proc.id::text||':'||v_procedure_item.id::text,v_user_id) returning * into v_ledger; insert into public.package_redemptions(user_id,patient_id,package_id,package_item_id,procedure_id,procedure_item_id,procedure_id_snapshot,procedure_item_id_snapshot,quantity,coverage_value_snapshot,ledger_movement_id,idempotency_key) values(v_user_id,p_patient_id,v_package.id,v_package_item.id,v_proc.id,v_procedure_item.id,v_proc.id,v_procedure_item.id,round(v_cov.quantity,3),v_procedure_item.coverage_value_snapshot,v_ledger.id,'redemption:'||v_proc.id::text||':'||v_procedure_item.id::text); end loop;
 insert into public.injectable_maps(procedure_id,patient_id,user_id,points) select v_proc.id,p_patient_id,v_user_id,m.value->'points' from jsonb_array_elements(p_injectable_maps) as m(value);
 if p_appointment_id is not null then update public.appointments set status='realizado' where id=p_appointment_id and user_id=v_user_id and patient_id=p_patient_id; if not found then raise exception using errcode='P0001',message='ATTENDANCE_APPOINTMENT_UPDATE_FAILED'; end if; end if;
 select * into v_proc from public.procedures where id=v_proc.id and user_id=v_user_id; return v_proc;
end; $$;

create or replace function public.create_procedure_with_injectable_draft_v3(p_idempotency_key uuid,p_patient_id uuid,p_appointment_id uuid,p_performed_at timestamptz,p_items jsonb,p_payment_entries jsonb,p_coverages jsonb,p_notes text,p_injectable_draft_id uuid,p_injectable_draft_revision bigint)
returns public.procedures language plpgsql security invoker set search_path=public,pg_temp as $$ declare v_proc public.procedures; begin if p_injectable_draft_id is null or p_injectable_draft_revision is null then raise exception using errcode='22023',message='INJECTABLE_DRAFT_ID_REVISION_REQUIRED'; end if; select * into v_proc from public.create_procedure_v3(p_idempotency_key,p_patient_id,p_appointment_id,p_performed_at,p_items,p_payment_entries,'[]'::jsonb,p_coverages,p_notes); perform public.finalize_injectable_map_v2(p_injectable_draft_id,p_injectable_draft_revision,v_proc.id,p_idempotency_key); return v_proc; end; $$;

create or replace function public.reverse_package_redemptions_before_procedure_delete_v1() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare v_redemption public.package_redemptions; v_existing uuid;
begin for v_redemption in select * from public.package_redemptions where procedure_id_snapshot=old.id and user_id=old.user_id order by id loop perform 1 from public.patient_package_items where id=v_redemption.package_item_id and user_id=old.user_id for update; select id into v_existing from public.patient_credit_ledger where user_id=old.user_id and idempotency_key='reversal:'||v_redemption.id::text; if not found then insert into public.patient_credit_ledger(user_id,patient_id,package_id,package_item_id,movement_type,quantity_delta,source_type,source_id,procedure_id,procedure_item_id,procedure_id_snapshot,procedure_item_id_snapshot,reason,idempotency_key,created_by) values(old.user_id,v_redemption.patient_id,v_redemption.package_id,v_redemption.package_item_id,'reversal',v_redemption.quantity,'procedure_reversal',v_redemption.id,old.id,v_redemption.procedure_item_id,old.id,v_redemption.procedure_item_id_snapshot,'Estorno automático por remoção do atendimento','reversal:'||v_redemption.id::text,old.user_id); end if; end loop; return old; end; $$;
create trigger procedures_reverse_package_redemptions_bd before delete on public.procedures for each row execute function public.reverse_package_redemptions_before_procedure_delete_v1();

revoke all on function public.create_procedure_v3(uuid,uuid,uuid,timestamptz,jsonb,jsonb,jsonb,jsonb,text) from public,anon;
revoke all on function public.create_procedure_with_injectable_draft_v3(uuid,uuid,uuid,timestamptz,jsonb,jsonb,jsonb,text,uuid,bigint) from public,anon;
grant execute on function public.create_procedure_v3(uuid,uuid,uuid,timestamptz,jsonb,jsonb,jsonb,jsonb,text) to authenticated;
grant execute on function public.create_procedure_with_injectable_draft_v3(uuid,uuid,uuid,timestamptz,jsonb,jsonb,jsonb,text,uuid,bigint) to authenticated;
revoke all on function public.reverse_package_redemptions_before_procedure_delete_v1() from public,anon,authenticated;
