-- Hub Giulia 3.2 — controlled package, voucher and package-sale operations.

alter table public.patient_packages add column sale_idempotency_key uuid;
create unique index patient_packages_user_sale_key_uidx on public.patient_packages(user_id, sale_idempotency_key) where sale_idempotency_key is not null;

create or replace function public.create_manual_package_v1(
  p_idempotency_key uuid, p_patient_id uuid, p_title text, p_source_type text, p_items jsonb,
  p_valid_from date default null, p_valid_until date default null, p_reason text default null, p_notes text default null
) returns public.patient_packages language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user_id uuid:=auth.uid(); v_package public.patient_packages; v_existing public.patient_packages; v_item_count integer; v_owned_count integer; v_total numeric(14,2);
begin
 if v_user_id is null then raise exception using errcode='P0001',message='PACKAGE_SESSION_REQUIRED'; end if;
 if p_idempotency_key is null then raise exception using errcode='22023',message='PACKAGE_IDEMPOTENCY_REQUIRED'; end if;
 if p_patient_id is null then raise exception using errcode='22023',message='PACKAGE_PATIENT_REQUIRED'; end if;
 if nullif(btrim(p_title),'') is null then raise exception using errcode='22023',message='PACKAGE_TITLE_REQUIRED'; end if;
 if p_source_type not in ('manual','complimentary') then raise exception using errcode='22023',message='PACKAGE_MANUAL_SOURCE_INVALID'; end if;
 if nullif(btrim(p_reason),'') is null then raise exception using errcode='22023',message='PACKAGE_REASON_REQUIRED'; end if;
 if p_valid_until is not null and p_valid_from is not null and p_valid_until<p_valid_from then raise exception using errcode='22023',message='PACKAGE_VALIDITY_INVALID'; end if;
 if jsonb_typeof(coalesce(p_items,'null'::jsonb))<>'array' or jsonb_array_length(p_items)=0 then raise exception using errcode='22023',message='PACKAGE_ITEMS_REQUIRED'; end if;
 select * into v_existing from public.patient_packages where user_id=v_user_id and creation_idempotency_key=p_idempotency_key; if found then return v_existing; end if;
 perform 1 from public.patients where id=p_patient_id and user_id=v_user_id; if not found then raise exception using errcode='P0001',message='PACKAGE_PATIENT_FORBIDDEN'; end if;
 if exists(select 1 from jsonb_to_recordset(p_items) as x(service_id uuid,quantity numeric,commercial_value numeric) where x.service_id is null or coalesce(x.quantity,0)<=0 or (x.commercial_value is not null and x.commercial_value<0)) then raise exception using errcode='22023',message='PACKAGE_ITEM_INVALID'; end if;
 select count(*) into v_item_count from jsonb_to_recordset(p_items) as x(service_id uuid,quantity numeric,commercial_value numeric);
 if (select count(distinct x.service_id) from jsonb_to_recordset(p_items) as x(service_id uuid,quantity numeric,commercial_value numeric))<>v_item_count then raise exception using errcode='22023',message='PACKAGE_DUPLICATE_SERVICE_ITEM'; end if;
 select count(*) into v_owned_count from public.services s join jsonb_to_recordset(p_items) as x(service_id uuid,quantity numeric,commercial_value numeric) on x.service_id=s.id where s.user_id=v_user_id;
 if v_owned_count<>v_item_count then raise exception using errcode='P0001',message='PACKAGE_SERVICE_FORBIDDEN'; end if;
 select round(coalesce(sum(coalesce(x.commercial_value,s.price*x.quantity)),0),2) into v_total from jsonb_to_recordset(p_items) as x(service_id uuid,quantity numeric,commercial_value numeric) join public.services s on s.id=x.service_id and s.user_id=v_user_id;
 insert into public.patient_packages(user_id,patient_id,title_snapshot,source_type,status,commercial_total_snapshot,valid_from,valid_until,notes,creation_reason,creation_idempotency_key,created_by) values(v_user_id,p_patient_id,btrim(p_title),p_source_type,'draft',v_total,p_valid_from,p_valid_until,p_notes,btrim(p_reason),p_idempotency_key,v_user_id) returning * into v_package;
 insert into public.patient_package_items(user_id,package_id,service_id,service_name_snapshot,quantity_granted,unit_label_snapshot,commercial_value_snapshot,sort_order)
 select v_user_id,v_package.id,s.id,s.name,round(x.quantity,3),'sessão',round(coalesce(x.commercial_value,s.price*x.quantity),2),x.ordinality::integer-1 from jsonb_to_recordset(p_items) with ordinality as x(service_id uuid,quantity numeric,commercial_value numeric,ordinality bigint) join public.services s on s.id=x.service_id and s.user_id=v_user_id;
 return v_package;
exception when unique_violation then select * into v_existing from public.patient_packages where user_id=v_user_id and creation_idempotency_key=p_idempotency_key; if found then return v_existing; end if; raise; end; $$;

create or replace function public.create_package_from_proposal_v1(p_proposal_version_id uuid,p_idempotency_key uuid,p_valid_from date default null,p_valid_until date default null,p_notes text default null)
returns public.patient_packages language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user_id uuid:=auth.uid(); v_version public.treatment_proposal_versions; v_package public.patient_packages; v_existing public.patient_packages; v_deal_id uuid; v_patient_id uuid;
begin
 if v_user_id is null then raise exception using errcode='P0001',message='PACKAGE_SESSION_REQUIRED'; end if;
 if p_proposal_version_id is null then raise exception using errcode='22023',message='PACKAGE_PROPOSAL_VERSION_REQUIRED'; end if;
 if p_idempotency_key is null then raise exception using errcode='22023',message='PACKAGE_IDEMPOTENCY_REQUIRED'; end if;
 if p_valid_until is not null and p_valid_from is not null and p_valid_until<p_valid_from then raise exception using errcode='22023',message='PACKAGE_VALIDITY_INVALID'; end if;
 select * into v_existing from public.patient_packages where user_id=v_user_id and source_proposal_version_id=p_proposal_version_id; if found then return v_existing; end if;
 select pv.* into v_version from public.treatment_proposal_versions pv where pv.id=p_proposal_version_id and pv.user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='PACKAGE_PROPOSAL_FORBIDDEN'; end if;
 if v_version.status<>'accepted' then raise exception using errcode='P0001',message='PACKAGE_PROPOSAL_NOT_ACCEPTED'; end if;
 select tp.deal_id,c.patient_id into v_deal_id,v_patient_id from public.treatment_proposals tp join public.deals d on d.id=tp.deal_id and d.user_id=tp.user_id join public.contacts c on c.id=d.contact_id and c.user_id=d.user_id where tp.id=v_version.proposal_id and tp.user_id=v_user_id;
 if v_patient_id is null then raise exception using errcode='P0001',message='PACKAGE_PROPOSAL_PATIENT_REQUIRED'; end if;
 if not exists(select 1 from public.treatment_proposal_items where proposal_version_id=v_version.id and user_id=v_user_id) then raise exception using errcode='P0001',message='PACKAGE_PROPOSAL_ITEMS_REQUIRED'; end if;
 insert into public.patient_packages(user_id,patient_id,title_snapshot,source_type,source_proposal_version_id,source_deal_id,status,commercial_total_snapshot,valid_from,valid_until,notes,creation_reason,creation_idempotency_key,created_by) values(v_user_id,v_patient_id,v_version.title,'proposal',v_version.id,v_deal_id,'draft',v_version.total_value,p_valid_from,p_valid_until,p_notes,'Proposta aceita',p_idempotency_key,v_user_id) returning * into v_package;
 insert into public.patient_package_items(user_id,package_id,service_id,service_name_snapshot,quantity_granted,unit_label_snapshot,commercial_value_snapshot,sort_order) select v_user_id,v_package.id,i.service_id,i.service_name_snapshot,i.quantity,i.unit_label,i.line_total,i.sort_order from public.treatment_proposal_items i where i.proposal_version_id=v_version.id and i.user_id=v_user_id order by i.sort_order,i.id;
 return v_package;
exception when unique_violation then select * into v_existing from public.patient_packages where user_id=v_user_id and source_proposal_version_id=p_proposal_version_id; if found then return v_existing; end if; select * into v_existing from public.patient_packages where user_id=v_user_id and creation_idempotency_key=p_idempotency_key; if found then return v_existing; end if; raise; end; $$;

create or replace function public.activate_package_v1(p_package_id uuid,p_idempotency_key uuid) returns public.patient_packages language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user_id uuid:=auth.uid(); v_package public.patient_packages; v_item public.patient_package_items;
begin
 if v_user_id is null then raise exception using errcode='P0001',message='PACKAGE_SESSION_REQUIRED'; end if; if p_idempotency_key is null then raise exception using errcode='22023',message='PACKAGE_ACTIVATION_KEY_REQUIRED'; end if;
 select * into v_package from public.patient_packages where id=p_package_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='PACKAGE_FORBIDDEN'; end if; if v_package.status='voided' then raise exception using errcode='P0001',message='PACKAGE_VOIDED'; end if; if v_package.status='active' then return v_package; end if;
 if not exists(select 1 from public.patient_package_items where package_id=v_package.id and user_id=v_user_id) then raise exception using errcode='P0001',message='PACKAGE_ITEMS_REQUIRED'; end if;
 for v_item in select * from public.patient_package_items where package_id=v_package.id and user_id=v_user_id order by id for update loop insert into public.patient_credit_ledger(user_id,patient_id,package_id,package_item_id,movement_type,quantity_delta,source_type,source_id,reason,idempotency_key,created_by) values(v_user_id,v_package.patient_id,v_package.id,v_item.id,'grant',v_item.quantity_granted,'activation',v_package.id,'Ativação inicial do pacote','activation:'||v_package.id::text||':'||v_item.id::text,v_user_id) on conflict(user_id,idempotency_key) do nothing; end loop;
 update public.patient_packages set status='active',activated_at=coalesce(activated_at,now()),activation_idempotency_key=coalesce(activation_idempotency_key,p_idempotency_key),updated_at=now() where id=v_package.id and user_id=v_user_id returning * into v_package; return v_package; end; $$;

create or replace function public.adjust_package_credit_v1(p_package_item_id uuid,p_quantity_delta numeric,p_reason text,p_idempotency_key uuid) returns public.patient_credit_ledger language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user_id uuid:=auth.uid(); v_item public.patient_package_items; v_package public.patient_packages; v_existing public.patient_credit_ledger; v_balance numeric(12,3); v_delta numeric(12,3);
begin
 if v_user_id is null then raise exception using errcode='P0001',message='PACKAGE_SESSION_REQUIRED'; end if; if p_idempotency_key is null then raise exception using errcode='22023',message='PACKAGE_ADJUSTMENT_KEY_REQUIRED'; end if; if nullif(btrim(p_reason),'') is null then raise exception using errcode='22023',message='PACKAGE_ADJUSTMENT_REASON_REQUIRED'; end if;
 v_delta:=round(coalesce(p_quantity_delta,0),3); if v_delta=0 then raise exception using errcode='22023',message='PACKAGE_ADJUSTMENT_DELTA_REQUIRED'; end if;
 select * into v_existing from public.patient_credit_ledger where user_id=v_user_id and idempotency_key='adjustment:'||p_idempotency_key::text; if found then return v_existing; end if;
 select * into v_item from public.patient_package_items where id=p_package_item_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='PACKAGE_ITEM_FORBIDDEN'; end if; select * into v_package from public.patient_packages where id=v_item.package_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='PACKAGE_FORBIDDEN'; end if; if v_package.status<>'active' then raise exception using errcode='P0001',message='PACKAGE_NOT_ACTIVE'; end if;
 select coalesce(sum(quantity_delta),0)::numeric(12,3) into v_balance from public.patient_credit_ledger where package_item_id=v_item.id and user_id=v_user_id; if v_balance+v_delta<0 then raise exception using errcode='P0001',message='PACKAGE_INSUFFICIENT_BALANCE'; end if;
 insert into public.patient_credit_ledger(user_id,patient_id,package_id,package_item_id,movement_type,quantity_delta,source_type,reason,idempotency_key,created_by) values(v_user_id,v_package.patient_id,v_package.id,v_item.id,'adjustment',v_delta,'manual_adjustment',btrim(p_reason),'adjustment:'||p_idempotency_key::text,v_user_id) returning * into v_existing; return v_existing; end; $$;

create or replace function public.void_package_v1(p_package_id uuid,p_reason text) returns public.patient_packages language plpgsql security definer set search_path=public,pg_temp as $$ declare v_user_id uuid:=auth.uid(); v_package public.patient_packages; begin if v_user_id is null then raise exception using errcode='P0001',message='PACKAGE_SESSION_REQUIRED'; end if; if nullif(btrim(p_reason),'') is null then raise exception using errcode='22023',message='PACKAGE_VOID_REASON_REQUIRED'; end if; select * into v_package from public.patient_packages where id=p_package_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='PACKAGE_FORBIDDEN'; end if; if v_package.status='voided' then return v_package; end if; update public.patient_packages set status='voided',voided_at=now(),void_reason=btrim(p_reason),updated_at=now() where id=v_package.id and user_id=v_user_id returning * into v_package; return v_package; end; $$;

create or replace function public.issue_voucher_v1(p_service_id uuid,p_quantity numeric,p_valid_until date default null,p_recipient_name text default null,p_recipient_phone text default null,p_patient_id uuid default null,p_source text default null,p_note text default null) returns public.vouchers language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user_id uuid:=auth.uid(); v_service public.services; v_voucher public.vouchers; v_code text; v_try integer:=0;
begin
 if v_user_id is null then raise exception using errcode='P0001',message='VOUCHER_SESSION_REQUIRED'; end if; if round(coalesce(p_quantity,0),3)<=0 then raise exception using errcode='22023',message='VOUCHER_QUANTITY_INVALID'; end if; if p_valid_until is not null and p_valid_until<current_date then raise exception using errcode='22023',message='VOUCHER_VALIDITY_INVALID'; end if;
 select * into v_service from public.services where id=p_service_id and user_id=v_user_id; if not found then raise exception using errcode='P0001',message='VOUCHER_SERVICE_FORBIDDEN'; end if; if p_patient_id is not null and not exists(select 1 from public.patients where id=p_patient_id and user_id=v_user_id) then raise exception using errcode='P0001',message='VOUCHER_PATIENT_FORBIDDEN'; end if;
 loop v_try:=v_try+1; v_code:='GIU-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)); begin insert into public.vouchers(user_id,code,normalized_code,status,service_id,service_name_snapshot,quantity,unit_label_snapshot,recipient_name,recipient_phone,patient_id,valid_until,source,note,created_by) values(v_user_id,v_code,v_code,'active',v_service.id,v_service.name,round(p_quantity,3),'sessão',nullif(btrim(p_recipient_name),''),nullif(btrim(p_recipient_phone),''),p_patient_id,p_valid_until,nullif(btrim(p_source),''),p_note,v_user_id) returning * into v_voucher; return v_voucher; exception when unique_violation then if v_try>=5 then raise; end if; end; end loop; end; $$;

create or replace function public.redeem_voucher_v1(p_code text,p_patient_id uuid) returns public.patient_packages language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user_id uuid:=auth.uid(); v_normalized text:=upper(regexp_replace(btrim(coalesce(p_code,'')),'\s+','','g')); v_voucher public.vouchers; v_package public.patient_packages; v_item public.patient_package_items;
begin
 if v_user_id is null then raise exception using errcode='P0001',message='VOUCHER_SESSION_REQUIRED'; end if; if v_normalized='' then raise exception using errcode='22023',message='VOUCHER_CODE_REQUIRED'; end if; if p_patient_id is null then raise exception using errcode='22023',message='VOUCHER_PATIENT_REQUIRED'; end if; if not exists(select 1 from public.patients where id=p_patient_id and user_id=v_user_id) then raise exception using errcode='P0001',message='VOUCHER_PATIENT_FORBIDDEN'; end if;
 select * into v_voucher from public.vouchers where user_id=v_user_id and normalized_code=v_normalized for update; if not found then raise exception using errcode='P0001',message='VOUCHER_NOT_FOUND'; end if;
 if v_voucher.status='redeemed' then if v_voucher.redeemed_by_patient_id<>p_patient_id then raise exception using errcode='P0001',message='VOUCHER_ALREADY_REDEEMED'; end if; select p.* into v_package from public.patient_packages p where p.id=v_voucher.redeemed_package_id and p.user_id=v_user_id; if found then return v_package; end if; raise exception using errcode='P0001',message='VOUCHER_REDEMPTION_INCONSISTENT'; end if;
 if v_voucher.status='voided' then raise exception using errcode='P0001',message='VOUCHER_VOIDED'; end if; if v_voucher.valid_until is not null and v_voucher.valid_until<current_date then raise exception using errcode='P0001',message='VOUCHER_EXPIRED'; end if; if v_voucher.patient_id is not null and v_voucher.patient_id<>p_patient_id then raise exception using errcode='P0001',message='VOUCHER_RECIPIENT_MISMATCH'; end if;
 insert into public.patient_packages(user_id,patient_id,title_snapshot,source_type,source_voucher_id,status,commercial_total_snapshot,valid_from,valid_until,activated_at,notes,creation_reason,created_by) values(v_user_id,p_patient_id,'Voucher '||v_voucher.service_name_snapshot,'voucher',v_voucher.id,'active',0,current_date,v_voucher.valid_until,now(),v_voucher.note,'Voucher resgatado',v_user_id) returning * into v_package;
 insert into public.patient_package_items(user_id,package_id,service_id,service_name_snapshot,quantity_granted,unit_label_snapshot,commercial_value_snapshot,sort_order) values(v_user_id,v_package.id,v_voucher.service_id,v_voucher.service_name_snapshot,v_voucher.quantity,v_voucher.unit_label_snapshot,0,0) returning * into v_item;
 insert into public.patient_credit_ledger(user_id,patient_id,package_id,package_item_id,movement_type,quantity_delta,source_type,source_id,reason,idempotency_key,created_by) values(v_user_id,p_patient_id,v_package.id,v_item.id,'grant',v_item.quantity_granted,'voucher',v_voucher.id,'Resgate de voucher','voucher:'||v_voucher.id::text,v_user_id);
 update public.vouchers set status='redeemed',redeemed_at=now(),redeemed_by_patient_id=p_patient_id,redeemed_package_id=v_package.id where id=v_voucher.id and user_id=v_user_id; return v_package;
exception when unique_violation then select p.* into v_package from public.patient_packages p join public.vouchers v on v.redeemed_package_id=p.id and v.user_id=p.user_id where v.user_id=v_user_id and v.normalized_code=v_normalized and v.redeemed_by_patient_id=p_patient_id; if found then return v_package; end if; raise; end; $$;

create or replace function public.void_voucher_v1(p_voucher_id uuid,p_reason text) returns public.vouchers language plpgsql security definer set search_path=public,pg_temp as $$ declare v_user_id uuid:=auth.uid(); v_voucher public.vouchers; begin if v_user_id is null then raise exception using errcode='P0001',message='VOUCHER_SESSION_REQUIRED'; end if; if nullif(btrim(p_reason),'') is null then raise exception using errcode='22023',message='VOUCHER_VOID_REASON_REQUIRED'; end if; select * into v_voucher from public.vouchers where id=p_voucher_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='VOUCHER_FORBIDDEN'; end if; if v_voucher.status='redeemed' then raise exception using errcode='P0001',message='VOUCHER_ALREADY_REDEEMED'; end if; if v_voucher.status='voided' then return v_voucher; end if; update public.vouchers set status='voided',voided_at=now(),void_reason=btrim(p_reason) where id=v_voucher.id and user_id=v_user_id returning * into v_voucher; return v_voucher; end; $$;

create or replace function public.record_package_sale_v1(p_package_id uuid,p_idempotency_key uuid,p_payment_entries jsonb) returns public.patient_packages language plpgsql security definer set search_path=public,pg_temp as $$
declare v_user_id uuid:=auth.uid(); v_package public.patient_packages; v_count integer; v_allocated numeric(14,2);
begin
 if v_user_id is null then raise exception using errcode='P0001',message='PACKAGE_SESSION_REQUIRED'; end if; if p_idempotency_key is null then raise exception using errcode='22023',message='PACKAGE_SALE_KEY_REQUIRED'; end if; select * into v_package from public.patient_packages where id=p_package_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='PACKAGE_FORBIDDEN'; end if; if v_package.status='voided' then raise exception using errcode='P0001',message='PACKAGE_VOIDED'; end if; if v_package.source_type in ('voucher','complimentary') then raise exception using errcode='P0001',message='PACKAGE_SALE_SOURCE_NOT_PAYABLE'; end if;
 if v_package.sale_recorded_at is not null then if v_package.sale_idempotency_key=p_idempotency_key then return v_package; end if; raise exception using errcode='P0001',message='PACKAGE_SALE_ALREADY_RECORDED'; end if; if v_package.commercial_total_snapshot<=0 then raise exception using errcode='P0001',message='PACKAGE_SALE_VALUE_REQUIRED'; end if; if jsonb_typeof(coalesce(p_payment_entries,'null'::jsonb))<>'array' or jsonb_array_length(p_payment_entries)=0 then raise exception using errcode='22023',message='PACKAGE_PAYMENTS_REQUIRED'; end if;
 if exists(select 1 from jsonb_to_recordset(p_payment_entries) as pay(method text,base_amount numeric,amount numeric,card_brand text,installments integer,fee_pct numeric,fee_value numeric,net_amount numeric,absorve_taxa boolean,scheduled_date date) where pay.method not in ('dinheiro','pix','cartao_credito','cartao_debito') or pay.base_amount is null or pay.base_amount<0 or pay.amount is null or pay.amount<0 or pay.net_amount is null or pay.net_amount<0 or coalesce(pay.installments,1)<1 or (pay.fee_pct is not null and (pay.fee_pct<0 or pay.fee_pct>100)) or (pay.fee_value is not null and pay.fee_value<0) or abs(pay.amount-coalesce(pay.fee_value,0)-pay.net_amount)>0.02 or (pay.method in ('cartao_credito','cartao_debito') and pay.card_brand not in ('master_visa','elo')) or (pay.method not in ('cartao_credito','cartao_debito') and pay.card_brand is not null) or (pay.method<>'cartao_credito' and coalesce(pay.installments,1)<>1)) then raise exception using errcode='22023',message='PACKAGE_PAYMENT_INVALID'; end if;
 select count(*),round(coalesce(sum(pay.base_amount),0),2) into v_count,v_allocated from jsonb_to_recordset(p_payment_entries) as pay(method text,base_amount numeric,amount numeric,card_brand text,installments integer,fee_pct numeric,fee_value numeric,net_amount numeric,absorve_taxa boolean,scheduled_date date); if v_count<1 then raise exception using errcode='22023',message='PACKAGE_PAYMENTS_REQUIRED'; end if; if abs(v_allocated-v_package.commercial_total_snapshot)>0.02 then raise exception using errcode='22023',message='PACKAGE_PAYMENT_TOTAL_MISMATCH'; end if;
 insert into public.package_payments(user_id,package_id,method,base_amount,amount,card_brand,installments,fee_pct,fee_value,net_amount,absorve_taxa,scheduled_date,paid_at) select v_user_id,v_package.id,pay.method,pay.base_amount,pay.amount,pay.card_brand,coalesce(pay.installments,1),pay.fee_pct,pay.fee_value,pay.net_amount,coalesce(pay.absorve_taxa,true),pay.scheduled_date,case when pay.scheduled_date is null or pay.scheduled_date<=current_date then now() else null end from jsonb_to_recordset(p_payment_entries) as pay(method text,base_amount numeric,amount numeric,card_brand text,installments integer,fee_pct numeric,fee_value numeric,net_amount numeric,absorve_taxa boolean,scheduled_date date);
 update public.patient_packages set sale_recorded_at=now(),sale_idempotency_key=p_idempotency_key,updated_at=now() where id=v_package.id and user_id=v_user_id returning * into v_package; return v_package; end; $$;

create or replace function public.mark_package_payment_paid_v1(p_payment_id uuid) returns public.package_payments language plpgsql security definer set search_path=public,pg_temp as $$ declare v_user_id uuid:=auth.uid(); v_payment public.package_payments; begin if v_user_id is null then raise exception using errcode='P0001',message='PACKAGE_SESSION_REQUIRED'; end if; select * into v_payment from public.package_payments where id=p_payment_id and user_id=v_user_id for update; if not found then raise exception using errcode='P0001',message='PACKAGE_PAYMENT_FORBIDDEN'; end if; if v_payment.paid_at is not null then return v_payment; end if; update public.package_payments set paid_at=now() where id=v_payment.id and user_id=v_user_id returning * into v_payment; return v_payment; end; $$;

create or replace function public.list_patient_entitlements_v1(p_patient_id uuid,p_service_ids uuid[] default null) returns setof public.patient_credit_item_balances_v language sql stable security invoker set search_path=public,pg_temp as $$ select b.* from public.patient_credit_item_balances_v b where b.patient_id=p_patient_id and (p_service_ids is null or b.service_id=any(p_service_ids)) order by b.package_title,b.service_name_snapshot,b.package_item_id; $$;

revoke all on function public.create_manual_package_v1(uuid,uuid,text,text,jsonb,date,date,text,text) from public,anon;
revoke all on function public.create_package_from_proposal_v1(uuid,uuid,date,date,text) from public,anon;
revoke all on function public.activate_package_v1(uuid,uuid) from public,anon;
revoke all on function public.adjust_package_credit_v1(uuid,numeric,text,uuid) from public,anon;
revoke all on function public.void_package_v1(uuid,text) from public,anon;
revoke all on function public.issue_voucher_v1(uuid,numeric,date,text,text,uuid,text,text) from public,anon;
revoke all on function public.redeem_voucher_v1(text,uuid) from public,anon;
revoke all on function public.void_voucher_v1(uuid,text) from public,anon;
revoke all on function public.record_package_sale_v1(uuid,uuid,jsonb) from public,anon;
revoke all on function public.mark_package_payment_paid_v1(uuid) from public,anon;
revoke all on function public.list_patient_entitlements_v1(uuid,uuid[]) from public,anon;
grant execute on function public.create_manual_package_v1(uuid,uuid,text,text,jsonb,date,date,text,text) to authenticated;
grant execute on function public.create_package_from_proposal_v1(uuid,uuid,date,date,text) to authenticated;
grant execute on function public.activate_package_v1(uuid,uuid) to authenticated;
grant execute on function public.adjust_package_credit_v1(uuid,numeric,text,uuid) to authenticated;
grant execute on function public.void_package_v1(uuid,text) to authenticated;
grant execute on function public.issue_voucher_v1(uuid,numeric,date,text,text,uuid,text,text) to authenticated;
grant execute on function public.redeem_voucher_v1(text,uuid) to authenticated;
grant execute on function public.void_voucher_v1(uuid,text) to authenticated;
grant execute on function public.record_package_sale_v1(uuid,uuid,jsonb) to authenticated;
grant execute on function public.mark_package_payment_paid_v1(uuid) to authenticated;
grant execute on function public.list_patient_entitlements_v1(uuid,uuid[]) to authenticated;
