-- Hub Giulia 3.9 — operational consolidation, attention, next action and data quality.
-- Additive/read-model only. No clinical or financial source-of-truth state is mutated.

create table if not exists public.data_quality_issue_suppressions (
  user_id uuid not null references auth.users(id) on delete cascade,
  issue_key text not null,
  issue_type text not null check (issue_type in ('possible_duplicate')),
  reason text not null default 'not_duplicate',
  created_at timestamptz not null default now(),
  primary key (user_id, issue_key)
);
alter table public.data_quality_issue_suppressions enable row level security;
drop policy if exists "data_quality_suppressions_select_own" on public.data_quality_issue_suppressions;
create policy "data_quality_suppressions_select_own" on public.data_quality_issue_suppressions for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "data_quality_suppressions_insert_own" on public.data_quality_issue_suppressions;
create policy "data_quality_suppressions_insert_own" on public.data_quality_issue_suppressions for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "data_quality_suppressions_delete_own" on public.data_quality_issue_suppressions;
create policy "data_quality_suppressions_delete_own" on public.data_quality_issue_suppressions for delete to authenticated using ((select auth.uid()) = user_id);
revoke all on table public.data_quality_issue_suppressions from public, anon;
grant select, insert, delete on table public.data_quality_issue_suppressions to authenticated;
create index if not exists data_quality_suppressions_user_type_idx on public.data_quality_issue_suppressions(user_id, issue_type, created_at desc);

create index if not exists patients_user_active_normalized_cpf_idx on public.patients(user_id, (regexp_replace(coalesce(cpf, ''), '\D', '', 'g'))) where archived_at is null and cpf is not null;
create index if not exists patients_user_active_normalized_phone_idx on public.patients(user_id, (public.communication_whatsapp_digits_v1(phone))) where archived_at is null and phone is not null;
create index if not exists patients_user_active_normalized_email_idx on public.patients(user_id, (lower(btrim(email)))) where archived_at is null and email is not null;

create or replace view public.operational_attention_v1 with (security_invoker = true) as
with communication_items as (
  select c.item_key attention_key,
    case when c.category='return' and c.priority='overdue' then 'clinical_overdue' when c.category='return' then 'clinical_due' when c.category='confirmation' then 'appointment_action' when c.category='crm' then 'communication_action' when c.category='proposal' then 'commercial_followup' when c.category='package' then 'credit_expiry' else 'communication_action' end priority_class,
    case when c.category='return' and c.priority='overdue' then 900 when c.category='return' and c.priority='today' then 850 when c.category='confirmation' and c.priority='today' then 760 when c.category='crm' and c.priority='overdue' then 680 when c.category='crm' then 640 when c.category='confirmation' and c.priority='tomorrow' then 700 when c.category='confirmation' then 620 when c.category='return' then 600 when c.category='proposal' and c.priority='overdue' then 500 when c.category='proposal' and c.priority='today' then 460 when c.category='proposal' then 420 when c.category='package' and c.priority='today' then 400 when c.category='package' and c.priority='tomorrow' then 360 when c.category='package' then 320 else 300 end priority_rank,
    c.category,c.source_type,c.source_id,c.patient_id,c.contact_id,c.display_name person_name,c.reason title,
    case when c.priority='overdue' then 'Atrasado' when c.priority='today' then 'Vence hoje' when c.priority='tomorrow' then 'Amanhã' else 'Próximo' end subtitle,
    c.due_at,c.priority source_priority,
    case when c.category='return' and c.patient_id is not null then '/retornos?patient_id='||c.patient_id::text when c.category='confirmation' then '/agenda?date='||to_char(c.due_at at time zone 'America/Sao_Paulo','YYYY-MM-DD') else c.target_route end route,
    case when c.category='return' then 'open_return' when c.category in ('confirmation','crm','proposal','package') then 'open_communication' else 'open_source' end action_type,
    case when c.category='return' then 'Ver retorno' when c.category='confirmation' then 'Confirmar' when c.category in ('crm','proposal','package') then 'Abrir comunicação' else 'Abrir' end action_label,
    case when c.category in ('confirmation','crm','proposal','package') then '/comunicacao?category='||c.category when c.category='return' and c.patient_id is not null then '/retornos?patient_id='||c.patient_id::text else c.target_route end action_route
  from public.communication_attention_v1 c where not c.is_snoozed and not c.is_suppressed_after_contact
), aftercare_items as (
  select a.item_key,
    case when coalesce((a.context->>'requires_professional_review')::boolean,false) then 'aftercare_review' when a.priority='overdue' then 'aftercare_overdue' else 'aftercare_due' end,
    case when coalesce((a.context->>'requires_professional_review')::boolean,false) then 880 when a.priority='overdue' then 840 else 800 end,
    'aftercare',a.source_type,a.source_id,a.patient_id,a.contact_id,a.display_name,a.reason,
    case when coalesce((a.context->>'requires_professional_review')::boolean,false) then 'Revisão profissional' when a.priority='overdue' then 'Atrasado' else 'Hoje' end,
    a.due_at,a.priority,case when a.patient_id is null then '/pacientes' else '/pacientes/'||a.patient_id::text end,'open_aftercare','Ver acompanhamento','/comunicacao?category=aftercare'
  from public.aftercare_communication_attention_v1 a where not a.is_snoozed and not a.is_suppressed_after_contact
), base_operational as (select * from communication_items union all select * from aftercare_items),
relationship_items as (
  select r.opportunity_key,'relationship_reactivation',200,'relationship',r.source_type,r.source_id,r.patient_id,r.contact_id,r.display_name,r.label,'Relacionamento',coalesce(r.sort_at,r.last_visit_at,now()),r.status,r.route,'open_relationship','Abrir relacionamento','/relacionamento?person_type='||r.person_type||'&person_id='||r.person_id::text
  from public.relationship_opportunity_sources_v1 r
  where r.opportunity_type='reactivation' and (r.snoozed_until is null or r.snoozed_until<=now())
    and not exists(select 1 from base_operational b where b.patient_id is not null and b.patient_id=r.patient_id)
), all_items as (select * from base_operational union all select * from relationship_items),
deduped as (select a.*,row_number() over(partition by a.attention_key order by a.priority_rank desc,a.due_at asc nulls last,a.source_id) rn from all_items a)
select attention_key,priority_class,priority_rank,category,source_type,source_id,patient_id,contact_id,person_name,title,subtitle,due_at,source_priority,route,action_type,action_label,action_route from deduped where rn=1;
revoke all on table public.operational_attention_v1 from public, anon;
grant select on table public.operational_attention_v1 to authenticated;

create or replace function public.list_operational_attention_v1(p_category text default null,p_limit integer default 20,p_offset integer default 0)
returns table(attention_key text,priority_class text,priority_rank integer,category text,source_type text,source_id uuid,patient_id uuid,contact_id uuid,person_name text,title text,subtitle text,due_at timestamptz,source_priority text,route text,action_type text,action_label text,action_route text)
language sql stable security invoker set search_path=public,pg_temp as $$
select a.attention_key,a.priority_class,a.priority_rank,a.category,a.source_type,a.source_id,a.patient_id,a.contact_id,a.person_name,a.title,a.subtitle,a.due_at,a.source_priority,a.route,a.action_type,a.action_label,a.action_route from public.operational_attention_v1 a where p_category is null or a.category=p_category order by a.priority_rank desc,a.due_at asc nulls last,a.attention_key limit least(greatest(coalesce(p_limit,20),1),100) offset greatest(coalesce(p_offset,0),0); $$;

create or replace function public.get_operational_attention_counts_v1() returns jsonb language sql stable security invoker set search_path=public,pg_temp as $$
select jsonb_build_object('total',count(*),'overdue',count(*) filter(where a.source_priority='overdue'),'return',count(*) filter(where a.category='return'),'aftercare',count(*) filter(where a.category='aftercare'),'confirmation',count(*) filter(where a.category='confirmation'),'communication',count(*) filter(where a.category in ('confirmation','crm','proposal','package')),'relationship',count(*) filter(where a.category='relationship')) from public.operational_attention_v1 a; $$;

create or replace function public.get_operational_day_summary_v1(p_day date default ((now() at time zone 'America/Sao_Paulo')::date)) returns jsonb language sql stable security invoker set search_path=public,pg_temp as $$
with bounds as (select (p_day::timestamp at time zone 'America/Sao_Paulo') start_at,((p_day+1)::timestamp at time zone 'America/Sao_Paulo') end_at),agenda as (select count(*) filter(where a.status not in ('cancelado','nao_compareceu')) total,count(*) filter(where a.status='confirmado') confirmed,count(*) filter(where a.status='pendente') pending,count(*) filter(where a.status='realizado') completed from public.appointments a cross join bounds b where a.user_id=auth.uid() and a.scheduled_at>=b.start_at and a.scheduled_at<b.end_at),next_appointment as (select jsonb_build_object('id',a.id,'patient_id',a.patient_id,'patient_name',p.name,'service_name',s.name,'scheduled_at',a.scheduled_at,'status',a.status,'route','/atendimento/'||a.id::text,'agenda_route','/agenda?date='||p_day::text) item from public.appointments a join public.patients p on p.id=a.patient_id and p.user_id=a.user_id left join public.services s on s.id=a.service_id and s.user_id=a.user_id cross join bounds b where a.user_id=auth.uid() and a.scheduled_at>=greatest(b.start_at,now()) and a.scheduled_at<b.end_at and a.status in ('pendente','confirmado') order by a.scheduled_at limit 1),procedures_today as (select count(*) performed,count(*) filter(where coalesce(pr.pending_amount,0)>0) pending_payment from public.procedures pr cross join bounds b where pr.user_id=auth.uid() and pr.performed_at>=b.start_at and pr.performed_at<b.end_at),future_returns as (select count(*) total from public.procedure_returns r where r.user_id=auth.uid() and r.completed_at is null and r.dismissed_at is null and r.window_start>p_day and r.window_start<=p_day+30),attention as (select count(*) total,count(*) filter(where category='aftercare') aftercare,count(*) filter(where category='return' and source_priority='overdue') overdue_returns,count(*) filter(where category='relationship') relationship from public.operational_attention_v1)
select jsonb_build_object('day',p_day,'agenda',jsonb_build_object('total',coalesce(ag.total,0),'confirmed',coalesce(ag.confirmed,0),'pending',coalesce(ag.pending,0),'completed',coalesce(ag.completed,0)),'next_appointment',(select item from next_appointment),'procedures_performed',coalesce(pt.performed,0),'pending_payment',coalesce(pt.pending_payment,0),'future_returns_30d',coalesce(fr.total,0),'attention_total',coalesce(atn.total,0),'aftercare_attention',coalesce(atn.aftercare,0),'overdue_returns',coalesce(atn.overdue_returns,0),'relationship_attention',coalesce(atn.relationship,0)) from agenda ag cross join procedures_today pt cross join future_returns fr cross join attention atn; $$;

create or replace function public.get_operational_week_summary_v1(p_start date default ((now() at time zone 'America/Sao_Paulo')::date)) returns jsonb language sql stable security invoker set search_path=public,pg_temp as $$
with bounds as (select (p_start::timestamp at time zone 'America/Sao_Paulo') start_at,((p_start+7)::timestamp at time zone 'America/Sao_Paulo') end_at),agenda as (select count(*) total from public.appointments a cross join bounds b where a.user_id=auth.uid() and a.scheduled_at>=b.start_at and a.scheduled_at<b.end_at and a.status not in ('cancelado','nao_compareceu')),attn as (select count(*) filter(where category='return' and source_priority='overdue') overdue_returns,count(*) filter(where category='aftercare') aftercare,count(*) filter(where category='relationship') relationship,count(*) filter(where category='package') expiring_credits from public.operational_attention_v1) select jsonb_build_object('start',p_start,'end_exclusive',p_start+7,'appointments',coalesce(agenda.total,0),'overdue_returns',coalesce(attn.overdue_returns,0),'aftercare',coalesce(attn.aftercare,0),'relationship',coalesce(attn.relationship,0),'expiring_credits',coalesce(attn.expiring_credits,0)) from agenda cross join attn; $$;

create or replace function public.get_patient_next_action_v1(p_patient_id uuid,p_appointment_id uuid default null) returns jsonb language sql stable security invoker set search_path=public,pg_temp as $$
with allowed_patient as (select p.id from public.patients p where p.id=p_patient_id and p.user_id=auth.uid() limit 1),today_appointment as (select 1000 rank,a.scheduled_at due_at,'appointment_today'::text source_type,a.id source_id,case when a.status='confirmado' then 'Atendimento hoje' else 'Atendimento hoje aguardando confirmação' end title,case when a.status='confirmado' then 'Iniciar atendimento' else 'Confirmar horário' end action_label,case when a.status='confirmado' then 'start_attendance' else 'open_communication' end action_type,case when a.status='confirmado' then '/atendimento/'||a.id::text else '/comunicacao?category=confirmation' end route from public.appointments a join allowed_patient p on p.id=a.patient_id where a.user_id=auth.uid() and a.status in ('pendente','confirmado') and (a.scheduled_at at time zone 'America/Sao_Paulo')::date=(now() at time zone 'America/Sao_Paulo')::date and (p_appointment_id is null or a.id=p_appointment_id) order by case when a.id=p_appointment_id then 0 else 1 end,a.scheduled_at limit 1),attention_action as (select a.priority_rank rank,a.due_at,a.source_type,a.source_id,a.title,a.action_label,a.action_type,a.action_route route from public.operational_attention_v1 a join allowed_patient p on p.id=a.patient_id order by a.priority_rank desc,a.due_at asc nulls last limit 1),future_appointment as (select 250 rank,a.scheduled_at due_at,'appointment'::text source_type,a.id source_id,'Próximo atendimento' title,'Ver agendamento' action_label,'open_appointment' action_type,'/agenda?date='||to_char(a.scheduled_at at time zone 'America/Sao_Paulo','YYYY-MM-DD') route from public.appointments a join allowed_patient p on p.id=a.patient_id where a.user_id=auth.uid() and a.status in ('pendente','confirmado') and a.scheduled_at>now() order by a.scheduled_at limit 1),candidates as (select * from today_appointment union all select * from attention_action union all select * from future_appointment),chosen as (select * from candidates order by rank desc,due_at asc nulls last limit 1) select case when not exists(select 1 from allowed_patient) or not exists(select 1 from chosen) then null else (select jsonb_build_object('source_type',c.source_type,'source_id',c.source_id,'title',c.title,'due_at',c.due_at,'action_type',c.action_type,'action_label',c.action_label,'route',c.route,'priority_rank',c.rank) from chosen c) end; $$;

create or replace view public.data_quality_possible_duplicates_v1 with (security_invoker=true) as
with normalized as (select p.id,p.user_id,p.name,p.phone,p.email,p.birth_date,p.created_at,case when length(regexp_replace(coalesce(p.cpf,''),'\D','','g'))=11 then regexp_replace(p.cpf,'\D','','g') else null end cpf_norm,public.communication_whatsapp_digits_v1(p.phone) phone_norm,case when position('@' in lower(btrim(coalesce(p.email,''))))>1 then lower(btrim(p.email)) else null end email_norm from public.patients p where p.user_id=auth.uid() and p.archived_at is null),pairs as (select p1.user_id,p1.id patient_a_id,p2.id patient_b_id,p1.name patient_a_name,p2.name patient_b_name,p1.phone patient_a_phone,p2.phone patient_b_phone,p1.email patient_a_email,p2.email patient_b_email,p1.birth_date patient_a_birth_date,p2.birth_date patient_b_birth_date,p1.created_at patient_a_created_at,p2.created_at patient_b_created_at,p1.cpf_norm patient_a_cpf_norm,p2.cpf_norm patient_b_cpf_norm,(p1.cpf_norm is not null and p1.cpf_norm=p2.cpf_norm) match_cpf,(p1.phone_norm is not null and p1.phone_norm=p2.phone_norm) match_phone,(p1.email_norm is not null and p1.email_norm=p2.email_norm) match_email from normalized p1 join normalized p2 on p2.user_id=p1.user_id and p1.id::text<p2.id::text and ((p1.cpf_norm is not null and p1.cpf_norm=p2.cpf_norm) or (p1.phone_norm is not null and p1.phone_norm=p2.phone_norm) or (p1.email_norm is not null and p1.email_norm=p2.email_norm))),with_keys as (select p.*,'possible_duplicate:'||p.patient_a_id::text||':'||p.patient_b_id::text issue_key from pairs p)
select k.issue_key,k.patient_a_id,k.patient_b_id,k.patient_a_name,k.patient_b_name,k.patient_a_phone,k.patient_b_phone,k.patient_a_email,k.patient_b_email,case when k.patient_a_cpf_norm is null then null else '***.***.***-'||right(k.patient_a_cpf_norm,2) end patient_a_cpf_masked,case when k.patient_b_cpf_norm is null then null else '***.***.***-'||right(k.patient_b_cpf_norm,2) end patient_b_cpf_masked,k.patient_a_birth_date,k.patient_b_birth_date,la.last_appointment_at patient_a_last_appointment_at,lb.last_appointment_at patient_b_last_appointment_at,k.patient_a_created_at,k.patient_b_created_at,k.match_cpf,k.match_phone,k.match_email,(case when k.match_cpf then 3 else 0 end+case when k.match_phone then 2 else 0 end+case when k.match_email then 1 else 0 end) confidence_weight from with_keys k left join lateral(select max(a.scheduled_at) last_appointment_at from public.appointments a where a.user_id=auth.uid() and a.patient_id=k.patient_a_id) la on true left join lateral(select max(a.scheduled_at) last_appointment_at from public.appointments a where a.user_id=auth.uid() and a.patient_id=k.patient_b_id) lb on true where not exists(select 1 from public.data_quality_issue_suppressions s where s.user_id=auth.uid() and s.issue_key=k.issue_key and s.issue_type='possible_duplicate');
revoke all on table public.data_quality_possible_duplicates_v1 from public,anon; grant select on table public.data_quality_possible_duplicates_v1 to authenticated;

create or replace view public.data_quality_issues_v1 with (security_invoker=true) as
select d.issue_key,'WARNING'::text severity,'possible_duplicate'::text category,d.patient_a_id patient_id,d.patient_b_id related_patient_id,'Possível duplicidade' title,concat_ws(' · ',case when d.match_cpf then 'CPF igual' end,case when d.match_phone then 'telefone igual' end,case when d.match_email then 'e-mail igual' end) detail,'/saude?issue='||d.issue_key route,'patient_pair' source_type,d.patient_a_id source_id,greatest(d.patient_a_created_at,d.patient_b_created_at) created_at from public.data_quality_possible_duplicates_v1 d
union all select 'patient_missing_phone:'||p.id,'INFO','incomplete_profile',p.id,null::uuid,'Paciente sem telefone','Cadastro permitido, mas sem telefone/WhatsApp para comunicação operacional.','/pacientes/'||p.id||'?tab=data&return_to=/saude','patient',p.id,p.created_at from public.patients p where p.user_id=auth.uid() and p.archived_at is null and public.communication_whatsapp_digits_v1(p.phone) is null
union all select 'patient_invalid_name:'||p.id,'WARNING','invalid_profile',p.id,null::uuid,'Nome de paciente precisa de revisão','Nome vazio ou muito curto para identificação operacional.','/pacientes/'||p.id||'?tab=data&return_to=/saude','patient',p.id,p.created_at from public.patients p where p.user_id=auth.uid() and p.archived_at is null and (nullif(btrim(p.name),'') is null or length(btrim(p.name))<2)
union all select 'contact_patient_reference:'||c.id,'ERROR','referential_integrity',c.patient_id,null::uuid,'Contato convertido sem paciente válido no mesmo tenant','contacts.patient_id não resolve para uma paciente pertencente à mesma conta.','/crm','contact',c.id,c.created_at from public.contacts c where c.user_id=auth.uid() and c.patient_id is not null and not exists(select 1 from public.patients p where p.id=c.patient_id and p.user_id=c.user_id)
union all select 'aftercare_plan_procedure:'||fp.id,'ERROR','referential_integrity',fp.patient_id,null::uuid,'Plano pós-atendimento sem procedimento válido','Plano ativo não resolve para o procedimento snapshot no mesmo tenant.',case when fp.patient_id is null then '/comunicacao?category=aftercare' else '/pacientes/'||fp.patient_id end,'procedure_followup_plan',fp.id,fp.created_at from public.procedure_followup_plans fp where fp.user_id=auth.uid() and fp.status='active' and fp.procedure_id_snapshot is not null and not exists(select 1 from public.procedures pr where pr.id=fp.procedure_id_snapshot and pr.user_id=fp.user_id)
union all select 'aftercare_task_plan:'||t.id,'ERROR','referential_integrity',t.patient_id,null::uuid,'Tarefa pós-atendimento sem plano válido','Tarefa não resolve para o plano de acompanhamento no mesmo tenant.','/comunicacao?category=aftercare','procedure_followup_task',t.id,t.created_at from public.procedure_followup_tasks t where t.user_id=auth.uid() and not exists(select 1 from public.procedure_followup_plans fp where fp.id=t.followup_plan_id and fp.user_id=t.user_id)
union all select 'return_procedure:'||r.id,'ERROR','referential_integrity',r.patient_id,null::uuid,'Retorno sem procedimento válido','Retorno não resolve para o procedimento de origem no mesmo tenant.','/retornos?patient_id='||r.patient_id,'procedure_return',r.id,r.created_at from public.procedure_returns r where r.user_id=auth.uid() and r.procedure_id is not null and not exists(select 1 from public.procedures pr where pr.id=r.procedure_id and pr.user_id=r.user_id)
union all select 'photo_storage_original:'||ph.id,'WARNING','storage_integrity',ph.patient_id,null::uuid,'Foto com arquivo original ausente','O registro clínico existe, mas o objeto original não foi localizado no Storage.','/pacientes/'||ph.patient_id||'?tab=photos&return_to=/saude','patient_photo',ph.id,ph.taken_at from public.patient_photos ph where ph.user_id=auth.uid() and ph.voided_at is null and ph.original_path is not null and not exists(select 1 from storage.objects o where o.bucket_id='patient-photos' and o.name=ph.original_path)
union all select 'contract_storage_pdf:'||c.id,'WARNING','storage_integrity',c.patient_id,null::uuid,'Contrato com PDF ausente','O contrato referencia um PDF que não foi localizado no Storage.','/pacientes/'||c.patient_id||'?tab=contracts&return_to=/saude','contract',c.id,c.created_at from public.contracts c where c.user_id=auth.uid() and c.voided_at is null and c.pdf_path is not null and not exists(select 1 from storage.objects o where o.bucket_id='contracts' and o.name=c.pdf_path)
union all select 'photo_storage_orphan:'||md5(o.name),'INFO','storage_orphan',null::uuid,null::uuid,'Arquivo de foto sem registro clínico','Objeto antigo no Storage não é referenciado por um registro ativo de Photos 2.0.','/saude','storage_object',o.id,o.created_at from storage.objects o where o.bucket_id='patient-photos' and o.created_at<now()-interval '24 hours' and not exists(select 1 from public.patient_photos ph where ph.user_id=auth.uid() and ph.voided_at is null and o.name in(ph.original_path,ph.preview_path,ph.thumbnail_path))
union all select 'contract_storage_orphan:'||md5(o.name),'INFO','storage_orphan',null::uuid,null::uuid,'Arquivo de contrato sem registro','Objeto antigo no Storage não é referenciado por um contrato ativo.','/saude','storage_object',o.id,o.created_at from storage.objects o where o.bucket_id='contracts' and o.created_at<now()-interval '24 hours' and not exists(select 1 from public.contracts c where c.user_id=auth.uid() and c.voided_at is null and o.name in(c.pdf_path,c.signature_path));
revoke all on table public.data_quality_issues_v1 from public,anon; grant select on table public.data_quality_issues_v1 to authenticated;

create or replace function public.list_data_quality_issues_v1(p_severity text default null,p_category text default null,p_search text default null,p_limit integer default 50,p_offset integer default 0) returns table(issue_key text,severity text,category text,patient_id uuid,related_patient_id uuid,title text,detail text,route text,source_type text,source_id uuid,created_at timestamptz) language sql stable security invoker set search_path=public,storage,pg_temp as $$ select i.issue_key,i.severity,i.category,i.patient_id,i.related_patient_id,i.title,i.detail,i.route,i.source_type,i.source_id,i.created_at from public.data_quality_issues_v1 i where (p_severity is null or i.severity=upper(p_severity)) and (p_category is null or i.category=p_category) and (nullif(btrim(coalesce(p_search,'')),'') is null or i.title ilike '%'||btrim(p_search)||'%' or i.detail ilike '%'||btrim(p_search)||'%' or exists(select 1 from public.patients p where p.user_id=auth.uid() and p.id in(i.patient_id,i.related_patient_id) and p.name ilike '%'||btrim(p_search)||'%')) order by case i.severity when 'ERROR' then 3 when 'WARNING' then 2 else 1 end desc,i.created_at desc,i.issue_key limit least(greatest(coalesce(p_limit,50),1),100) offset greatest(coalesce(p_offset,0),0); $$;
create or replace function public.get_data_quality_summary_v1() returns jsonb language sql stable security invoker set search_path=public,storage,pg_temp as $$ select jsonb_build_object('critical',count(*) filter(where severity='ERROR'),'warning',count(*) filter(where severity='WARNING'),'info',count(*) filter(where severity='INFO'),'possible_duplicate',count(*) filter(where category='possible_duplicate'),'incomplete_data',count(*) filter(where category in('incomplete_profile','invalid_profile')),'orphan_or_inconsistency',count(*) filter(where category in('referential_integrity','storage_integrity','storage_orphan'))) from public.data_quality_issues_v1; $$;
create or replace function public.dismiss_data_quality_issue_v1(p_issue_key text,p_reason text default 'not_duplicate') returns void language plpgsql security invoker set search_path=public,pg_temp as $$ begin if auth.uid() is null then raise exception 'authentication required' using errcode='42501'; end if; if p_issue_key is null or p_issue_key not like 'possible_duplicate:%' then raise exception 'only possible duplicate pairs can be suppressed' using errcode='22023'; end if; insert into public.data_quality_issue_suppressions(user_id,issue_key,issue_type,reason) values(auth.uid(),p_issue_key,'possible_duplicate',coalesce(nullif(btrim(p_reason),''),'not_duplicate')) on conflict(user_id,issue_key) do update set reason=excluded.reason,created_at=now(); end; $$;
create or replace function public.get_possible_duplicate_pair_v1(p_issue_key text) returns table(issue_key text,patient_a_id uuid,patient_b_id uuid,patient_a_name text,patient_b_name text,patient_a_phone text,patient_b_phone text,patient_a_email text,patient_b_email text,patient_a_cpf_masked text,patient_b_cpf_masked text,patient_a_birth_date date,patient_b_birth_date date,patient_a_last_appointment_at timestamptz,patient_b_last_appointment_at timestamptz,patient_a_created_at timestamptz,patient_b_created_at timestamptz,match_cpf boolean,match_phone boolean,match_email boolean,confidence_weight integer) language sql stable security invoker set search_path=public,pg_temp as $$ select d.* from public.data_quality_possible_duplicates_v1 d where d.issue_key=p_issue_key limit 1; $$;

revoke all on function public.list_operational_attention_v1(text,integer,integer) from public,anon;
revoke all on function public.get_operational_attention_counts_v1() from public,anon;
revoke all on function public.get_operational_day_summary_v1(date) from public,anon;
revoke all on function public.get_operational_week_summary_v1(date) from public,anon;
revoke all on function public.get_patient_next_action_v1(uuid,uuid) from public,anon;
revoke all on function public.list_data_quality_issues_v1(text,text,text,integer,integer) from public,anon;
revoke all on function public.get_data_quality_summary_v1() from public,anon;
revoke all on function public.dismiss_data_quality_issue_v1(text,text) from public,anon;
revoke all on function public.get_possible_duplicate_pair_v1(text) from public,anon;
grant execute on function public.list_operational_attention_v1(text,integer,integer) to authenticated;
grant execute on function public.get_operational_attention_counts_v1() to authenticated;
grant execute on function public.get_operational_day_summary_v1(date) to authenticated;
grant execute on function public.get_operational_week_summary_v1(date) to authenticated;
grant execute on function public.get_patient_next_action_v1(uuid,uuid) to authenticated;
grant execute on function public.list_data_quality_issues_v1(text,text,text,integer,integer) to authenticated;
grant execute on function public.get_data_quality_summary_v1() to authenticated;
grant execute on function public.dismiss_data_quality_issue_v1(text,text) to authenticated;
grant execute on function public.get_possible_duplicate_pair_v1(text) to authenticated;
