-- Hub Giulia 3.9 — respect Returns 2.0 encapsulation.
create or replace function public.get_operational_day_summary_v1(p_day date default ((now() at time zone 'America/Sao_Paulo')::date)) returns jsonb language sql stable security invoker set search_path=public,pg_temp as $$
with bounds as(select (p_day::timestamp at time zone 'America/Sao_Paulo') start_at,((p_day+1)::timestamp at time zone 'America/Sao_Paulo') end_at),agenda as(select count(*) filter(where a.status not in('cancelado','nao_compareceu')) total,count(*) filter(where a.status='confirmado') confirmed,count(*) filter(where a.status='pendente') pending,count(*) filter(where a.status='realizado') completed from public.appointments a cross join bounds b where a.user_id=auth.uid() and a.scheduled_at>=b.start_at and a.scheduled_at<b.end_at),next_appointment as(select jsonb_build_object('id',a.id,'patient_id',a.patient_id,'patient_name',p.name,'service_name',s.name,'scheduled_at',a.scheduled_at,'status',a.status,'route','/atendimento/'||a.id::text,'agenda_route','/agenda?date='||p_day::text) item from public.appointments a join public.patients p on p.id=a.patient_id and p.user_id=a.user_id left join public.services s on s.id=a.service_id and s.user_id=a.user_id cross join bounds b where a.user_id=auth.uid() and a.scheduled_at>=greatest(b.start_at,now()) and a.scheduled_at<b.end_at and a.status in('pendente','confirmado') order by a.scheduled_at limit 1),procedures_today as(select count(*) performed,count(*) filter(where coalesce(pr.pending_amount,0)>0) pending_payment from public.procedures pr cross join bounds b where pr.user_id=auth.uid() and pr.performed_at>=b.start_at and pr.performed_at<b.end_at),future_returns as(select count(*) total from public.list_procedure_returns_v2() r where r.completed_at is null and r.dismissed_at is null and r.window_start>p_day and r.window_start<=p_day+30),attention as(select count(*) total,count(*) filter(where category='aftercare') aftercare,count(*) filter(where category='return' and source_priority='overdue') overdue_returns,count(*) filter(where category='relationship') relationship from public.operational_attention_v1)
select jsonb_build_object('day',p_day,'agenda',jsonb_build_object('total',coalesce(ag.total,0),'confirmed',coalesce(ag.confirmed,0),'pending',coalesce(ag.pending,0),'completed',coalesce(ag.completed,0)),'next_appointment',(select item from next_appointment),'procedures_performed',coalesce(pt.performed,0),'pending_payment',coalesce(pt.pending_payment,0),'future_returns_30d',coalesce(fr.total,0),'attention_total',coalesce(atn.total,0),'aftercare_attention',coalesce(atn.aftercare,0),'overdue_returns',coalesce(atn.overdue_returns,0),'relationship_attention',coalesce(atn.relationship,0)) from agenda ag cross join procedures_today pt cross join future_returns fr cross join attention atn; $$;

create or replace view public.data_quality_issues_v1 with (security_invoker=true) as
select d.issue_key,'WARNING'::text severity,'possible_duplicate'::text category,d.patient_a_id patient_id,d.patient_b_id related_patient_id,'Possível duplicidade' title,concat_ws(' · ',case when d.match_cpf then 'CPF igual' end,case when d.match_phone then 'telefone igual' end,case when d.match_email then 'e-mail igual' end) detail,'/saude?issue='||d.issue_key route,'patient_pair' source_type,d.patient_a_id source_id,greatest(d.patient_a_created_at,d.patient_b_created_at) created_at from public.data_quality_possible_duplicates_v1 d
union all select 'patient_missing_phone:'||p.id,'INFO','incomplete_profile',p.id,null::uuid,'Paciente sem telefone','Cadastro permitido, mas sem telefone/WhatsApp para comunicação operacional.','/pacientes/'||p.id||'?tab=data&return_to=/saude','patient',p.id,p.created_at from public.patients p where p.user_id=auth.uid() and p.archived_at is null and public.communication_whatsapp_digits_v1(p.phone) is null
union all select 'patient_invalid_name:'||p.id,'WARNING','invalid_profile',p.id,null::uuid,'Nome de paciente precisa de revisão','Nome vazio ou muito curto para identificação operacional.','/pacientes/'||p.id||'?tab=data&return_to=/saude','patient',p.id,p.created_at from public.patients p where p.user_id=auth.uid() and p.archived_at is null and(nullif(btrim(p.name),'') is null or length(btrim(p.name))<2)
union all select 'contact_patient_reference:'||c.id,'ERROR','referential_integrity',c.patient_id,null::uuid,'Contato convertido sem paciente válido no mesmo tenant','contacts.patient_id não resolve para uma paciente pertencente à mesma conta.','/crm','contact',c.id,c.created_at from public.contacts c where c.user_id=auth.uid() and c.patient_id is not null and not exists(select 1 from public.patients p where p.id=c.patient_id and p.user_id=c.user_id)
union all select 'aftercare_plan_procedure:'||fp.id,'ERROR','referential_integrity',fp.patient_id,null::uuid,'Plano pós-atendimento sem procedimento válido','Plano ativo não resolve para o procedimento snapshot no mesmo tenant.',case when fp.patient_id is null then '/comunicacao?category=aftercare' else '/pacientes/'||fp.patient_id end,'procedure_followup_plan',fp.id,fp.created_at from public.procedure_followup_plans fp where fp.user_id=auth.uid() and fp.status='active' and fp.procedure_id_snapshot is not null and not exists(select 1 from public.procedures pr where pr.id=fp.procedure_id_snapshot and pr.user_id=fp.user_id)
union all select 'aftercare_task_plan:'||t.id,'ERROR','referential_integrity',t.patient_id,null::uuid,'Tarefa pós-atendimento sem plano válido','Tarefa não resolve para o plano de acompanhamento no mesmo tenant.','/comunicacao?category=aftercare','procedure_followup_task',t.id,t.created_at from public.procedure_followup_tasks t where t.user_id=auth.uid() and not exists(select 1 from public.procedure_followup_plans fp where fp.id=t.followup_plan_id and fp.user_id=t.user_id)
union all select 'return_procedure:'||r.id,'ERROR','referential_integrity',r.patient_id,null::uuid,'Retorno sem procedimento válido','Retorno não resolve para o procedimento de origem no mesmo tenant.','/retornos?patient_id='||r.patient_id,'procedure_return',r.id,r.created_at from public.list_procedure_returns_v2() r where r.procedure_id is not null and not exists(select 1 from public.procedures pr where pr.id=r.procedure_id and pr.user_id=auth.uid())
union all select 'photo_storage_original:'||ph.id,'WARNING','storage_integrity',ph.patient_id,null::uuid,'Foto com arquivo original ausente','O registro clínico existe, mas o objeto original não foi localizado no Storage.','/pacientes/'||ph.patient_id||'?tab=photos&return_to=/saude','patient_photo',ph.id,ph.taken_at from public.patient_photos ph where ph.user_id=auth.uid() and ph.voided_at is null and ph.original_path is not null and not exists(select 1 from storage.objects o where o.bucket_id='patient-photos' and o.name=ph.original_path)
union all select 'contract_storage_pdf:'||c.id,'WARNING','storage_integrity',c.patient_id,null::uuid,'Contrato com PDF ausente','O contrato referencia um PDF que não foi localizado no Storage.','/pacientes/'||c.patient_id||'?tab=contracts&return_to=/saude','contract',c.id,c.created_at from public.contracts c where c.user_id=auth.uid() and c.voided_at is null and c.pdf_path is not null and not exists(select 1 from storage.objects o where o.bucket_id='contracts' and o.name=c.pdf_path)
union all select 'photo_storage_orphan:'||md5(o.name),'INFO','storage_orphan',null::uuid,null::uuid,'Arquivo de foto sem registro clínico','Objeto antigo no Storage não é referenciado por um registro ativo de Photos 2.0.','/saude','storage_object',o.id,o.created_at from storage.objects o where o.bucket_id='patient-photos' and o.created_at<now()-interval '24 hours' and not exists(select 1 from public.patient_photos ph where ph.user_id=auth.uid() and ph.voided_at is null and o.name in(ph.original_path,ph.preview_path,ph.thumbnail_path))
union all select 'contract_storage_orphan:'||md5(o.name),'INFO','storage_orphan',null::uuid,null::uuid,'Arquivo de contrato sem registro','Objeto antigo no Storage não é referenciado por um contrato ativo.','/saude','storage_object',o.id,o.created_at from storage.objects o where o.bucket_id='contracts' and o.created_at<now()-interval '24 hours' and not exists(select 1 from public.contracts c where c.user_id=auth.uid() and c.voided_at is null and o.name in(c.pdf_path,c.signature_path));
revoke all on table public.data_quality_issues_v1 from public,anon;
grant select on table public.data_quality_issues_v1 to authenticated;
