-- Hub Giulia 3.9 — explicit tenant guard for Storage orphan diagnostics.
create or replace view public.data_quality_issues_v1 with (security_invoker=true) as
select d.issue_key,'WARNING'::text severity,'possible_duplicate'::text category,d.patient_a_id patient_id,d.patient_b_id related_patient_id,'Possível duplicidade' title,concat_ws(' · ',case when d.match_cpf then 'CPF igual' end,case when d.match_phone then 'telefone igual' end,case when d.match_email then 'e-mail igual' end) detail,'/saude?issue='||d.issue_key route,'patient_pair' source_type,d.patient_a_id source_id,greatest(d.patient_a_created_at,d.patient_b_created_at) created_at from public.data_quality_possible_duplicates_v1 d
union all select 'patient_missing_phone:'||p.id,'INFO','incomplete_profile',p.id,null::uuid,'Paciente sem telefone','Cadastro permitido, mas sem telefone/WhatsApp para comunicação operacional.','/pacientes/'||p.id||'?tab=data&return_to=/saude','patient',p.id,p.created_at from public.patients p where p.user_id=auth.uid() and p.archived_at is null and public.communication_whatsapp_digits_v1(p.phone) is null
union all select 'patient_invalid_name:'||p.id,'WARNING','invalid_profile',p.id,null::uuid,'Nome de paciente precisa de revisão','Nome vazio ou muito curto para identificação operacional.','/pacientes/'||p.id||'?tab=data&return_to=/saude','patient',p.id,p.created_at from public.patients p where p.user_id=auth.uid() and p.archived_at is null and(nullif(btrim(p.name),'') is null or length(btrim(p.name))<2)
union all select 'contact_patient_reference:'||c.id,'ERROR','referential_integrity',c.patient_id,null::uuid,'Contato convertido sem paciente válido no mesmo tenant','contacts.patient_id não resolve para uma paciente pertencente à mesma conta.','/crm','contact',c.id,c.created_at from public.contacts c where c.user_id=auth.uid() and c.patient_id is not null and not exists(select 1 from public.patients p where p.id=c.patient_id and p.user_id=c.user_id)
union all select 'aftercare_plan_procedure:'||fp.id,'ERROR','referential_integrity',fp.patient_id,null::uuid,'Plano pós-atendimento sem procedimento válido','Plano ativo não resolve para o procedimento snapshot no mesmo tenant.',case when fp.patient_id is null then '/comunicacao?category=aftercare' else '/pacientes/'||fp.patient_id end,'procedure_followup_plan',fp.id,fp.created_at from public.procedure_followup_plans fp where fp.user_id=auth.uid() and fp.status='active' and fp.procedure_id_snapshot is not null and not exists(select 1 from public.procedures pr where pr.id=fp.procedure_id_snapshot and pr.user_id=fp.user_id)
union all select 'aftercare_task_plan:'||t.id,'ERROR','referential_integrity',t.patient_id,null::uuid,'Tarefa pós-atendimento sem plano válido','Tarefa não resolve para o plano de acompanhamento no mesmo tenant.','/comunicacao?category=aftercare','procedure_followup_task',t.id,t.created_at from public.procedure_followup_tasks t where t.user_id=auth.uid() and not exists(select 1 from public.procedure_followup_plans fp where fp.id=t.followup_plan_id and fp.user_id=t.user_id)
union all select 'return_procedure:'||r.id,'ERROR','referential_integrity',r.patient_id,null::uuid,'Retorno sem procedimento válido','Retorno não resolve para o procedimento de origem no mesmo tenant.','/retornos?patient_id='||r.patient_id,'procedure_return',r.id,r.created_at from public.list_procedure_returns_v2() r where r.procedure_id is not null and not exists(select 1 from public.procedures pr where pr.id=r.procedure_id and pr.user_id=auth.uid())
union all select 'photo_storage_original:'||ph.id,'WARNING','storage_integrity',ph.patient_id,null::uuid,'Foto com arquivo original ausente','O registro clínico existe, mas o objeto original não foi localizado no Storage.','/pacientes/'||ph.patient_id||'?tab=photos&return_to=/saude','patient_photo',ph.id,ph.taken_at from public.patient_photos ph where ph.user_id=auth.uid() and ph.voided_at is null and ph.original_path is not null and not exists(select 1 from storage.objects o where o.bucket_id='patient-photos' and o.name=ph.original_path)
union all select 'contract_storage_pdf:'||c.id,'WARNING','storage_integrity',c.patient_id,null::uuid,'Contrato com PDF ausente','O contrato referencia um PDF que não foi localizado no Storage.','/pacientes/'||c.patient_id||'?tab=contracts&return_to=/saude','contract',c.id,c.created_at from public.contracts c where c.user_id=auth.uid() and c.voided_at is null and c.pdf_path is not null and not exists(select 1 from storage.objects o where o.bucket_id='contracts' and o.name=c.pdf_path)
union all select 'photo_storage_orphan:'||md5(o.name),'INFO','storage_orphan',null::uuid,null::uuid,'Arquivo de foto sem registro clínico','Objeto antigo no Storage não é referenciado por um registro ativo de Photos 2.0.','/saude','storage_object',o.id,o.created_at from storage.objects o where o.bucket_id='patient-photos' and split_part(o.name,'/',1)=auth.uid()::text and o.created_at<now()-interval '24 hours' and not exists(select 1 from public.patient_photos ph where ph.user_id=auth.uid() and ph.voided_at is null and o.name in(ph.original_path,ph.preview_path,ph.thumbnail_path))
union all select 'contract_storage_orphan:'||md5(o.name),'INFO','storage_orphan',null::uuid,null::uuid,'Arquivo de contrato sem registro','Objeto antigo no Storage não é referenciado por um contrato ativo.','/saude','storage_object',o.id,o.created_at from storage.objects o where o.bucket_id='contracts' and split_part(o.name,'/',1)=auth.uid()::text and o.created_at<now()-interval '24 hours' and not exists(select 1 from public.contracts c where c.user_id=auth.uid() and c.voided_at is null and o.name in(c.pdf_path,c.signature_path));
revoke all on table public.data_quality_issues_v1 from public,anon;
grant select on table public.data_quality_issues_v1 to authenticated;
