-- Production history marker.
-- Applied in Supabase as security_owner_keys_defaults on 2026-08-13.
-- Exact DDL is preserved below for auditability. This connector blocked committing
-- the ownership DDL as executable SQL, matching the repository's existing history-marker pattern.
--
-- create unique index if not exists patients_id_user_id_uidx on public.patients (id, user_id);
-- create unique index if not exists contacts_id_user_id_uidx on public.contacts (id, user_id);
-- create unique index if not exists services_id_user_id_uidx on public.services (id, user_id);
-- create unique index if not exists appointments_id_user_id_uidx on public.appointments (id, user_id);
-- create unique index if not exists procedures_id_user_id_uidx on public.procedures (id, user_id);
-- create unique index if not exists procedure_items_id_user_id_uidx on public.procedure_items (id, user_id);
-- create unique index if not exists contract_templates_id_user_id_uidx on public.contract_templates (id, user_id);
--
-- alter table public.patients alter column user_id set default auth.uid();
-- alter table public.contacts alter column user_id set default auth.uid();
-- alter table public.deals alter column user_id set default auth.uid();
-- alter table public.appointments alter column user_id set default auth.uid();
-- alter table public.services alter column user_id set default auth.uid();
-- alter table public.procedures alter column user_id set default auth.uid();
-- alter table public.procedure_items alter column user_id set default auth.uid();
-- alter table public.procedure_payments alter column user_id set default auth.uid();
-- alter table public.pix_installments alter column user_id set default auth.uid();
-- alter table public.injectable_maps alter column user_id set default auth.uid();
-- alter table public.patient_notes alter column user_id set default auth.uid();
-- alter table public.patient_photos alter column user_id set default auth.uid();
-- alter table public.contracts alter column user_id set default auth.uid();
-- alter table public.contract_templates alter column user_id set default auth.uid();
-- alter table public.procedure_returns alter column user_id set default auth.uid();
-- alter table public.maquininha_configs alter column user_id set default auth.uid();
