create or replace view public.relationship_person_context_v1 with (security_invoker=true) as
with params as (select (select auth.uid()) user_id),
linked_contacts as (select c.user_id,c.patient_id,c.id contact_id from public.contacts c join params x on x.user_id=c.user_id where c.patient_id is not null and c.archived_at is null),
last_procedure as (select p.user_id,p.patient_id,max(p.performed_at) last_procedure_at from public.procedures p join params x on x.user_id=p.user_id group by p.user_id,p.patient_id),
legacy_appointment as (select a.user_id,a.patient_id,max(a.scheduled_at) last_realized_appointment_at from public.appointments a join params x on x.user_id=a.user_id where a.status='realizado' group by a.user_id,a.patient_id),
next_appointment as (select a.user_id,a.patient_id,min(a.scheduled_at) next_appointment_at from public.appointments a join params x on x.user_id=a.user_id where a.status in ('pendente','confirmado') and a.scheduled_at>=now() group by a.user_id,a.patient_id),
communication_contact_events as (select m.user_id,case when m.patient_id is not null or c.patient_id is not null then 'patient' else 'contact' end person_type,coalesce(m.patient_id,c.patient_id,m.contact_id) person_id,m.sent_at occurred_at from public.communication_messages m join params x on x.user_id=m.user_id left join public.contacts c on c.id=m.contact_id and c.user_id=m.user_id where m.status='sent_manual' and coalesce(m.patient_id,c.patient_id,m.contact_id) is not null),
crm_contact_events as (select a.user_id,case when c.patient_id is not null then 'patient' else 'contact' end person_type,coalesce(c.patient_id,c.id) person_id,a.occurred_at from public.crm_activities a join params x on x.user_id=a.user_id join public.contacts c on c.id=a.contact_id and c.user_id=a.user_id where a.activity_type='contact' and not(coalesce(a.metadata,'{}'::jsonb)?'communication_message_id')),
real_contact_events as (select * from communication_contact_events union all select * from crm_contact_events),
last_contact as (select user_id,person_type,person_id,max(occurred_at) last_contact_at from real_contact_events group by user_id,person_type,person_id),
aftercare_active as (select distinct fp.user_id,fp.patient_id from public.procedure_followup_plans fp join params x on x.user_id=fp.user_id where fp.status='active' and fp.patient_id is not null and ((fp.instructions_snapshot is not null and fp.manual_delivery_at is null and not exists(select 1 from public.communication_messages m where m.user_id=fp.user_id and m.source_type='procedure_followup_plan' and m.source_id=fp.id and m.context='aftercare_instructions')) or exists(select 1 from public.procedure_followup_tasks t where t.user_id=fp.user_id and t.followup_plan_id=fp.id and t.status='pending'))),
patient_people as (select p.user_id,'patient'::text person_type,p.id person_id,p.id patient_id,lc.contact_id,p.name display_name,p.phone,coalesce(lp.last_procedure_at,la.last_realized_appointment_at) last_visit_at,na.next_appointment_at,rlc.last_contact_at,coalesce(aa.patient_id is not null,false) has_active_aftercare,st.snoozed_until from public.patients p join params x on x.user_id=p.user_id left join linked_contacts lc on lc.user_id=p.user_id and lc.patient_id=p.id left join last_procedure lp on lp.user_id=p.user_id and lp.patient_id=p.id left join legacy_appointment la on la.user_id=p.user_id and la.patient_id=p.id left join next_appointment na on na.user_id=p.user_id and na.patient_id=p.id left join last_contact rlc on rlc.user_id=p.user_id and rlc.person_type='patient' and rlc.person_id=p.id left join aftercare_active aa on aa.user_id=p.user_id and aa.patient_id=p.id left join public.communication_attention_state st on st.user_id=p.user_id and st.item_key='relationship:patient:'||p.id::text where p.archived_at is null),
contact_people as (select c.user_id,'contact'::text person_type,c.id person_id,null::uuid patient_id,c.id contact_id,c.name display_name,c.phone,null::timestamptz last_visit_at,null::timestamptz next_appointment_at,rlc.last_contact_at,false has_active_aftercare,st.snoozed_until from public.contacts c join params x on x.user_id=c.user_id left join last_contact rlc on rlc.user_id=c.user_id and rlc.person_type='contact' and rlc.person_id=c.id left join public.communication_attention_state st on st.user_id=c.user_id and st.item_key='relationship:contact:'||c.id::text where c.patient_id is null and c.archived_at is null)
select * from patient_people union all select * from contact_people;
revoke all on table public.relationship_person_context_v1 from anon;
grant select on table public.relationship_person_context_v1 to authenticated;

create or replace view public.relationship_opportunity_sources_v1 with (security_invoker=true) as
with params as (select (select auth.uid()) user_id,(now() at time zone 'America/Sao_Paulo')::date today,now() now_at,coalesce((select returns_enabled from public.relationship_preferences where user_id=(select auth.uid())),true) returns_enabled,coalesce((select proposals_enabled from public.relationship_preferences where user_id=(select auth.uid())),true) proposals_enabled,coalesce((select credits_enabled from public.relationship_preferences where user_id=(select auth.uid())),true) credits_enabled,coalesce((select reactivation_enabled from public.relationship_preferences where user_id=(select auth.uid())),true) reactivation_enabled,coalesce((select reactivation_after_days from public.relationship_preferences where user_id=(select auth.uid())),180) reactivation_after_days,coalesce((select recent_contact_cooldown_days from public.relationship_preferences where user_id=(select auth.uid())),7) recent_contact_cooldown_days,coalesce((select proposal_followup_days from public.communication_preferences where user_id=(select auth.uid())),2) proposal_followup_days,coalesce((select package_expiry_days from public.communication_preferences where user_id=(select auth.uid())),15) package_expiry_days),
people as (select pc.* from public.relationship_person_context_v1 pc join params x on x.user_id=pc.user_id),
return_sources as (select p.user_id,p.person_type,p.person_id,p.patient_id,p.contact_id,p.display_name,p.phone,p.last_visit_at,p.next_appointment_at,p.last_contact_at,p.snoozed_until,'return:'||r.id::text opportunity_key,'return'::text opportunity_type,case when r.window_end<x.today then 'return_overdue' when r.window_start<=x.today then 'return_due' else 'return_upcoming' end priority_class,case when r.window_end<x.today then 500 when r.window_start<=x.today then 450 else 350 end priority_rank,((r.window_end::timestamp+time '09:00') at time zone 'America/Sao_Paulo') sort_at,case when r.window_end<x.today then 'Retorno atrasado há '||(x.today-r.window_end)::text||' dia'||case when(x.today-r.window_end)=1 then '' else 's' end when r.window_start<=x.today then 'Retorno disponível' else 'Retorno abre em '||(r.window_start-x.today)::text||' dia'||case when(r.window_start-x.today)=1 then '' else 's' end end label,'procedure_return'::text source_type,r.id source_id,case when r.window_end<x.today then 'overdue' when r.window_start<=x.today then 'due' else 'upcoming' end status,r.window_end due_date,case when r.window_end<x.today then x.today-r.window_end else 0 end age_days,null::numeric amount,null::jsonb remaining,null::date expires_on,'/retornos?patient_id='||r.patient_id::text route,'return:'||r.id::text communication_item_key,'procedure_return'::text template_key,jsonb_build_object('window_start',r.window_start,'window_end',r.window_end,'return_type',r.return_type,'service_name',r.service_name_snapshot) context from public.procedure_returns r join params x on x.user_id=r.user_id and x.returns_enabled join people p on p.user_id=r.user_id and p.person_type='patient' and p.patient_id=r.patient_id left join public.appointments a on a.id=r.appointment_id and a.user_id=r.user_id where r.completed_at is null and r.dismissed_at is null and r.window_start<=x.today+5 and(r.appointment_id is null or a.status in('cancelado','nao_compareceu')) and(r.contacted_at is null or r.contacted_at<=x.now_at-make_interval(days=>x.recent_contact_cooldown_days))),
latest_proposal as (select v.*,row_number() over(partition by v.proposal_id order by v.version_number desc,v.id desc) rn from public.treatment_proposal_versions v join params x on x.user_id=v.user_id),
proposal_sources as (select p.user_id,p.person_type,p.person_id,p.patient_id,p.contact_id,p.display_name,p.phone,p.last_visit_at,p.next_appointment_at,p.last_contact_at,p.snoozed_until,'proposal:'||v.id::text opportunity_key,'proposal'::text opportunity_type,'proposal_followup'::text priority_class,300 priority_rank,greatest(v.sent_at,coalesce(p.last_contact_at,v.sent_at))+make_interval(days=>x.proposal_followup_days) sort_at,'Proposta sem contato recente há '||greatest(0,floor(extract(epoch from(x.now_at-greatest(v.sent_at,coalesce(p.last_contact_at,v.sent_at))))/86400))::int::text||' dia(s)' label,'proposal_version'::text source_type,v.id source_id,'open'::text status,v.valid_until due_date,greatest(0,floor(extract(epoch from(x.now_at-v.sent_at))/86400))::int age_days,v.total_value amount,null::jsonb remaining,v.valid_until expires_on,'/crm/deals/'||d.id::text||'/proposals/'||tp.id::text route,'proposal:'||v.id::text||':followup' communication_item_key,'proposal_followup'::text template_key,jsonb_build_object('proposal_id',tp.id,'deal_id',d.id,'proposal_title',v.title,'total_value',v.total_value,'sent_at',v.sent_at,'valid_until',v.valid_until) context from latest_proposal v join params x on x.user_id=v.user_id and x.proposals_enabled join public.treatment_proposals tp on tp.id=v.proposal_id and tp.user_id=v.user_id join public.deals d on d.id=tp.deal_id and d.user_id=tp.user_id join public.contacts c on c.id=d.contact_id and c.user_id=d.user_id join people p on p.user_id=c.user_id and p.person_type=case when c.patient_id is not null then 'patient' else 'contact' end and p.person_id=coalesce(c.patient_id,c.id) where v.rn=1 and v.status='issued' and v.sent_at is not null and(v.valid_until is null or v.valid_until>=x.today) and greatest(v.sent_at,coalesce(p.last_contact_at,v.sent_at))+make_interval(days=>x.proposal_followup_days)<=x.now_at),
credit_items as (select b.*,x.today,x.package_expiry_days from public.patient_credit_item_balances_v b join params x on x.user_id=b.user_id and x.credits_enabled where b.package_status='active' and b.raw_balance>0 and(b.valid_from is null or b.valid_from<=x.today) and b.valid_until is not null and b.valid_until>=x.today and b.valid_until<=x.today+x.package_expiry_days),
credit_rollup as (select b.user_id,b.patient_id,b.package_id,max(b.package_title) package_title,max(b.valid_until) valid_until,jsonb_agg(jsonb_build_object('package_item_id',b.package_item_id,'service_name',b.service_name_snapshot,'balance',b.raw_balance,'unit_label',b.unit_label_snapshot) order by b.service_name_snapshot,b.package_item_id) remaining from credit_items b group by b.user_id,b.patient_id,b.package_id),
credit_sources as (select p.user_id,p.person_type,p.person_id,p.patient_id,p.contact_id,p.display_name,p.phone,p.last_visit_at,p.next_appointment_at,p.last_contact_at,p.snoozed_until,'package:'||cr.package_id::text||':expiry' opportunity_key,'credit'::text opportunity_type,'credit_expiry'::text priority_class,400 priority_rank,((cr.valid_until::timestamp+time '09:00') at time zone 'America/Sao_Paulo') sort_at,case when cr.valid_until=x.today then 'Crédito vence hoje' else 'Crédito vence em '||(cr.valid_until-x.today)::text||' dia'||case when(cr.valid_until-x.today)=1 then '' else 's' end end label,'package'::text source_type,cr.package_id source_id,'active'::text status,cr.valid_until due_date,0 age_days,null::numeric amount,cr.remaining,cr.valid_until expires_on,'/pacotes'::text route,'package:'||cr.package_id::text||':expiry' communication_item_key,'package_expiry'::text template_key,jsonb_build_object('package_title',cr.package_title,'valid_until',cr.valid_until) context from credit_rollup cr join params x on x.user_id=cr.user_id join people p on p.user_id=cr.user_id and p.person_type='patient' and p.patient_id=cr.patient_id where p.last_contact_at is null or p.last_contact_at<=x.now_at-make_interval(days=>x.recent_contact_cooldown_days)),
reactivation_sources as (select p.user_id,p.person_type,p.person_id,p.patient_id,p.contact_id,p.display_name,p.phone,p.last_visit_at,p.next_appointment_at,p.last_contact_at,p.snoozed_until,'reactivation:'||p.patient_id::text opportunity_key,'reactivation'::text opportunity_type,'reactivation'::text priority_class,100 priority_rank,p.last_visit_at sort_at,'Sem atendimento há '||(x.today-(p.last_visit_at at time zone 'America/Sao_Paulo')::date)::text||' dias' label,'relationship_patient'::text source_type,p.patient_id source_id,'inactive'::text status,null::date due_date,(x.today-(p.last_visit_at at time zone 'America/Sao_Paulo')::date) age_days,null::numeric amount,null::jsonb remaining,null::date expires_on,'/pacientes/'||p.patient_id::text route,'relationship:patient:'||p.patient_id::text||':reactivation' communication_item_key,'relationship_reactivation'::text template_key,jsonb_build_object('last_visit_at',p.last_visit_at) context from people p join params x on x.user_id=p.user_id and x.reactivation_enabled where p.person_type='patient' and p.last_visit_at is not null and(p.last_visit_at at time zone 'America/Sao_Paulo')::date<=x.today-x.reactivation_after_days and p.next_appointment_at is null and not p.has_active_aftercare and(p.last_contact_at is null or p.last_contact_at<=x.now_at-make_interval(days=>x.recent_contact_cooldown_days)) and not exists(select 1 from public.procedure_returns r where r.user_id=p.user_id and r.patient_id=p.patient_id and r.completed_at is null and r.dismissed_at is null)),
all_sources as(select * from return_sources union all select * from credit_sources union all select * from proposal_sources union all select * from reactivation_sources)
select * from all_sources;
revoke all on table public.relationship_opportunity_sources_v1 from anon;
grant select on table public.relationship_opportunity_sources_v1 to authenticated;

create or replace function public.list_relationship_opportunities_v1(p_category text default null,p_search text default null,p_include_snoozed boolean default false,p_limit integer default 50,p_offset integer default 0)
returns table(person_type text,person_id uuid,patient_id uuid,contact_id uuid,display_name text,phone text,last_visit_at timestamptz,next_appointment_at timestamptz,last_contact_at timestamptz,opportunity_count bigint,highest_priority_type text,opportunities jsonb,snoozed_until timestamptz,target_route text)
language sql security invoker set search_path='public','pg_temp' as $function$
with source as(select s.* from public.relationship_opportunity_sources_v1 s where s.user_id=(select auth.uid())),wanted_people as(select distinct s.person_type,s.person_id from source s where(p_category is null or p_category='' or s.opportunity_type=p_category) and(nullif(btrim(left(coalesce(p_search,''),80)),'') is null or s.display_name ilike '%'||btrim(left(p_search,80))||'%' or regexp_replace(coalesce(s.phone,''),'\D','','g') like '%'||regexp_replace(btrim(left(p_search,80)),'\D','','g')||'%') and(coalesce(p_include_snoozed,false) or s.snoozed_until is null or s.snoozed_until<=now())),ranked as(select s.*,row_number() over(partition by s.person_type,s.person_id order by s.priority_rank desc,s.sort_at asc nulls last,s.opportunity_key) rn from source s join wanted_people w using(person_type,person_id)) select r.person_type,r.person_id,max(r.patient_id::text)::uuid,max(r.contact_id::text)::uuid,max(r.display_name),max(r.phone),max(r.last_visit_at),max(r.next_appointment_at),max(r.last_contact_at),count(*)::bigint,max(r.opportunity_type) filter(where r.rn=1),jsonb_agg(jsonb_build_object('key',r.opportunity_key,'type',r.opportunity_type,'priority_class',r.priority_class,'source_type',r.source_type,'source_id',r.source_id,'status',r.status,'label',r.label,'due_date',r.due_date,'age_days',r.age_days,'amount',r.amount,'remaining',r.remaining,'expires_on',r.expires_on,'route',r.route,'communication_item_key',r.communication_item_key,'template_key',r.template_key,'context',r.context) order by r.priority_rank desc,r.sort_at asc nulls last,r.opportunity_key),max(r.snoozed_until),case when r.person_type='patient' then '/pacientes/'||r.person_id::text else '/crm' end from ranked r group by r.person_type,r.person_id order by max(r.priority_rank) desc,min(r.sort_at) asc nulls last,max(r.display_name) limit greatest(1,least(coalesce(p_limit,50),100)) offset greatest(coalesce(p_offset,0),0);
$function$;
create or replace function public.get_relationship_person_v1(p_person_type text,p_person_id uuid) returns table(person_type text,person_id uuid,patient_id uuid,contact_id uuid,display_name text,phone text,last_visit_at timestamptz,next_appointment_at timestamptz,last_contact_at timestamptz,opportunities jsonb,snoozed_until timestamptz,target_route text) language sql security invoker set search_path='public','pg_temp' as $function$ select s.person_type,s.person_id,max(s.patient_id::text)::uuid,max(s.contact_id::text)::uuid,max(s.display_name),max(s.phone),max(s.last_visit_at),max(s.next_appointment_at),max(s.last_contact_at),jsonb_agg(jsonb_build_object('key',s.opportunity_key,'type',s.opportunity_type,'priority_class',s.priority_class,'source_type',s.source_type,'source_id',s.source_id,'status',s.status,'label',s.label,'due_date',s.due_date,'age_days',s.age_days,'amount',s.amount,'remaining',s.remaining,'expires_on',s.expires_on,'route',s.route,'communication_item_key',s.communication_item_key,'template_key',s.template_key,'context',s.context) order by s.priority_rank desc,s.sort_at asc nulls last,s.opportunity_key),max(s.snoozed_until),case when s.person_type='patient' then '/pacientes/'||s.person_id::text else '/crm' end from public.relationship_opportunity_sources_v1 s where s.user_id=(select auth.uid()) and s.person_type=p_person_type and s.person_id=p_person_id group by s.person_type,s.person_id; $function$;
create or replace function public.get_relationship_opportunity_counts_v1() returns jsonb language sql security invoker set search_path='public','pg_temp' as $function$ with source as(select * from public.relationship_opportunity_sources_v1 where user_id=(select auth.uid()) and(snoozed_until is null or snoozed_until<=now())),people as(select distinct person_type,person_id from source) select jsonb_build_object('total',(select count(*) from people),'return',(select count(*) from(select distinct person_type,person_id from source where opportunity_type='return')x),'proposal',(select count(*) from(select distinct person_type,person_id from source where opportunity_type='proposal')x),'credit',(select count(*) from(select distinct person_type,person_id from source where opportunity_type='credit')x),'reactivation',(select count(*) from(select distinct person_type,person_id from source where opportunity_type='reactivation')x),'snoozed',(select count(*) from(select distinct person_type,person_id from public.relationship_opportunity_sources_v1 where user_id=(select auth.uid()) and snoozed_until>now())x)); $function$;
revoke all on function public.list_relationship_opportunities_v1(text,text,boolean,integer,integer) from public,anon;
revoke all on function public.get_relationship_person_v1(text,uuid) from public,anon;
revoke all on function public.get_relationship_opportunity_counts_v1() from public,anon;
grant execute on function public.list_relationship_opportunities_v1(text,text,boolean,integer,integer) to authenticated;
grant execute on function public.get_relationship_person_v1(text,uuid) to authenticated;
grant execute on function public.get_relationship_opportunity_counts_v1() to authenticated;
